/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/SetWebScene.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/SetWebScene.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model010" position={[15.605, 5.895, -2.34]} rotation={[-Math.PI / 2, 0, 0]} scale={5.264}>
          <group name="root005">
            <group name="GLTF_SceneRootNode005" rotation={[Math.PI / 2, 0, 0]}>
              <group name="root_0">
                <group name="node_id214_1" position={[-0.027, -0.216, 0.545]} rotation={[0, 0.236, 0]} scale={0.004} />
              </group>
            </group>
          </group>
        </group>
        <group name="node_438b64c4_089f_4a5f_8090_789b6782eff0" position={[11.015, 5.525, -3.927]} rotation={[Math.PI / 2, 0, 2.706]} scale={[3.339, 1.875, 1.875]} />
        <group name="node_1c880b5b_d49e_4b2d_a593_cb85239bf439" position={[10.988, 5.525, -3.986]} rotation={[Math.PI / 2, 0, -0.435]} scale={0.654} />
        <group name="node_89ea1a5a_c5cc_40f2_a3ba_1d9ae86a321c" position={[16.779, 8.06, 2.35]} rotation={[-2.763, 0.912, -2.454]} />
        <group name="node_ba6c5aab_e43d_4245_a409_913c5825aad5" position={[11.246, 5.525, -3.431]} rotation={[Math.PI / 2, 0, -0.435]} scale={0.654} />
        <group name="node_2d3306f9_b681_4efa_8633_91e0b05bf7c2" position={[14.159, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />
        <group name="node_a2def745_ecdb_4bb7_ac83_1e242e8dc004" position={[14.159, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />
        <group name="node_72c1c9ce_bcbb_4e55_8fb9_391c09196dcc" position={[14.159, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />
        <group name="Armature" position={[15.763, 4.073, 1.208]} rotation={[Math.PI / 2, 0, 0.902]} scale={0.009}>
          <primitive object={nodes.mixamorigHips} />
          <group name="Mouth_mouth_0001">
            <skinnedMesh name="Mouth_mouth_0001_1" geometry={nodes.Mouth_mouth_0001_1.geometry} material={materials['mouth.001']} skeleton={nodes.Mouth_mouth_0001_1.skeleton} />
            <skinnedMesh name="Mouth_mouth_0001_2" geometry={nodes.Mouth_mouth_0001_2.geometry} material={materials['eyes.001']} skeleton={nodes.Mouth_mouth_0001_2.skeleton} />
            <skinnedMesh name="Mouth_mouth_0001_3" geometry={nodes.Mouth_mouth_0001_3.geometry} material={materials['eye_brows.001']} skeleton={nodes.Mouth_mouth_0001_3.skeleton} />
            <skinnedMesh name="Mouth_mouth_0001_4" geometry={nodes.Mouth_mouth_0001_4.geometry} material={materials['hair.001']} skeleton={nodes.Mouth_mouth_0001_4.skeleton} />
            <skinnedMesh name="Mouth_mouth_0001_5" geometry={nodes.Mouth_mouth_0001_5.geometry} material={materials['skin.001']} skeleton={nodes.Mouth_mouth_0001_5.skeleton} />
            <skinnedMesh name="Mouth_mouth_0001_6" geometry={nodes.Mouth_mouth_0001_6.geometry} material={materials['t_shirt.001']} skeleton={nodes.Mouth_mouth_0001_6.skeleton} />
            <skinnedMesh name="Mouth_mouth_0001_7" geometry={nodes.Mouth_mouth_0001_7.geometry} material={materials['pant.001']} skeleton={nodes.Mouth_mouth_0001_7.skeleton} />
            <skinnedMesh name="Mouth_mouth_0001_8" geometry={nodes.Mouth_mouth_0001_8.geometry} material={materials['shoes.001']} skeleton={nodes.Mouth_mouth_0001_8.skeleton} />
          </group>
        </group>
        <mesh name="Cube_Material002_0001" geometry={nodes.Cube_Material002_0001.geometry} material={materials['Material.011']} position={[16.791, 3.909, 2.252]} rotation={[-1.535, -0.024, 0.023]} scale={0.095} />
        <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials['material.001']} position={[15.73, 4.457, 0.558]} rotation={[0, 0.236, 0]} scale={0.021} />
        <mesh name="Object_5001" geometry={nodes.Object_5001.geometry} material={materials['material.001']} position={[12.775, 4.457, 0.558]} rotation={[0, 0.236, 0]} scale={0.021} />
        <mesh name="Cube_Material002_0002" geometry={nodes.Cube_Material002_0002.geometry} material={materials['Material.011']} position={[11.745, 3.909, 2.104]} rotation={[-1.553, 0.039, 1.75]} scale={0.095} />
        <mesh name="Cube_Material002_0003" geometry={nodes.Cube_Material002_0003.geometry} material={materials['Material.011']} position={[16.526, 3.908, -2.121]} rotation={[-1.535, -0.024, 0.023]} scale={0.095} />
        <mesh name="Material_001-material001" geometry={nodes['Material_001-material001'].geometry} material={materials['Material.020']} position={[15.583, 4.031, 1.864]} rotation={[-Math.PI / 2, 0, 2.358]} scale={[0.089, 0.043, 0.089]} />
        <mesh name="Material_001-material002" geometry={nodes['Material_001-material002'].geometry} material={materials['Material.020']} position={[12.219, 3.9, -1.904]} rotation={[-Math.PI / 2, 0, 2.358]} scale={[0.089, 0.043, 0.089]} />
        <mesh name="node_11098d9c_ee66_44a5_a0f4_f949e0f9a01c_mesh0" geometry={nodes.node_11098d9c_ee66_44a5_a0f4_f949e0f9a01c_mesh0.geometry} material={materials['Material.020']} position={[14.159, 3.611, 0]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="node_1c880b5b_d49e_4b2d_a593_cb85239bf439_mesh0" geometry={nodes.node_1c880b5b_d49e_4b2d_a593_cb85239bf439_mesh0.geometry} material={materials['Material.006']} position={[11.015, 5.525, -3.927]} rotation={[Math.PI / 2, 0, 2.706]} scale={[3.339, 1.875, 1.875]} />
        <mesh name="node_438b64c4_089f_4a5f_8090_789b6782eff0_mesh0" geometry={nodes.node_438b64c4_089f_4a5f_8090_789b6782eff0_mesh0.geometry} material={materials['mat_23.002']} position={[11.007, 5.525, -3.944]} rotation={[Math.PI / 2, 0, -0.435]} scale={[0.848, 0.561, 0.838]} />
        <mesh name="node_af4bf03e_50f9_4b43_8d48_3b5badb8f34e_mesh0" geometry={nodes.node_af4bf03e_50f9_4b43_8d48_3b5badb8f34e_mesh0.geometry} material={materials['mat_15.002']} position={[14.159, 3.599, 0]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="node_99779b56_450e_444e_bf89_8bb883eacab4_mesh0" geometry={nodes.node_99779b56_450e_444e_bf89_8bb883eacab4_mesh0.geometry} material={materials['mat_12.002']} position={[11.579, 5.267, -1.797]} rotation={[Math.PI / 2, 0, -2.371]} scale={[0.73, 0.785, 0.785]} />
        <mesh name="node_aacfec3d_ae09_46b7_8848_238e322581a0_mesh0" geometry={nodes.node_aacfec3d_ae09_46b7_8848_238e322581a0_mesh0.geometry} material={materials['mat_12.002']} position={[11.645, 4.494, -1.58]} rotation={[0.7, -0.634, 2.58]} scale={0.71} />
        <mesh name="node_f3aa2127_e49a_4871_9c3a_495852ddee80_mesh0" geometry={nodes.node_f3aa2127_e49a_4871_9c3a_495852ddee80_mesh0.geometry} material={materials['mat_12.002']} position={[11.668, 4.648, -1.936]} rotation={[-0.01, -0.242, 2.517]} scale={0.619} />
        <mesh name="node_d3384d8c_cc81_4401_903a_dba5a34b5f75_mesh0" geometry={nodes.node_d3384d8c_cc81_4401_903a_dba5a34b5f75_mesh0.geometry} material={materials['mat_3.002']} position={[15.574, 4.849, 1.571]} rotation={[1.465, 0.5, -1.363]} scale={0.862} />
        <mesh name="Text001" geometry={nodes.Text001.geometry} material={materials['Material.028']} position={[14.089, 4.583, 0.475]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.011, 0.008, 0.011]} />
        <mesh name="node_33212657_deac_4e36_aed6_dd36c34f55e2_mesh0001" geometry={nodes.node_33212657_deac_4e36_aed6_dd36c34f55e2_mesh0001.geometry} material={materials['Material.013']} position={[12.42, 6.799, -0.58]} rotation={[2.808, -0.414, -0.151]} scale={0.697} />
        <mesh name="node_d2d5b2a1_746e_44c7_96c7_50adc24f8d8b_mesh0001" geometry={nodes.node_d2d5b2a1_746e_44c7_96c7_50adc24f8d8b_mesh0001.geometry} material={nodes.node_d2d5b2a1_746e_44c7_96c7_50adc24f8d8b_mesh0001.material} position={[12.42, 6.799, -0.58]} rotation={[2.808, -0.414, -0.151]} scale={0.697} />
        <mesh name="node_e587de53_9e89_46a2_a1d4_43c0d850810e_mesh0001" geometry={nodes.node_e587de53_9e89_46a2_a1d4_43c0d850810e_mesh0001.geometry} material={materials['Material.007']} position={[12.42, 6.799, -0.58]} rotation={[2.808, -0.414, -0.151]} scale={0.697} />
        <mesh name="Engineer_Man_Engineer_0002" geometry={nodes.Engineer_Man_Engineer_0002.geometry} material={materials.Engineer} position={[16, 4.888, 1.502]} rotation={[Math.PI, -1.206, Math.PI]} scale={0.914} />
        <mesh name="Teacher_Woman_Teacher_0001" geometry={nodes.Teacher_Woman_Teacher_0001.geometry} material={materials.Teacher} position={[12.292, 4.782, -2.478]} rotation={[-0.442, -1.366, -0.413]} scale={0.948} />
        <mesh name="Engineer_Man_Engineer_0003" geometry={nodes.Engineer_Man_Engineer_0003.geometry} material={materials.Engineer} position={[11.461, 4.791, -1.632]} rotation={[-Math.PI, 0.993, -Math.PI]} scale={0.914} />
        <mesh name="Delivery_Man_Delivery_Man001_0001" geometry={nodes.Delivery_Man_Delivery_Man001_0001.geometry} material={materials['Delivery Man.001']} position={[12.272, 4.82, -1.636]} rotation={[Math.PI, -0.615, Math.PI]} scale={0.968} />
        <mesh name="Delivery_Woman001_Doctor_0001" geometry={nodes.Delivery_Woman001_Doctor_0001.geometry} material={materials.Doctor} position={[11.564, 4.748, 1.343]} rotation={[Math.PI, -0.022, Math.PI]} scale={0.93} />
        <mesh name="node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0001" geometry={nodes.node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0001.geometry} material={materials['Material.019']} position={[13.949, 7.69, 0.177]} rotation={[Math.PI / 2, 0, 0]} scale={0.009} />
        <mesh name="node_41b68b41_de9a_423d_829f_669dfa469edd_mesh0001" geometry={nodes.node_41b68b41_de9a_423d_829f_669dfa469edd_mesh0001.geometry} material={materials['Material.006']} position={[13.949, 7.69, 0.177]} rotation={[Math.PI / 2, 0, -0.309]} scale={0.441} />
        <mesh name="node_a24b4965_6852_41ba_b37a_60e5ba245102_mesh0001" geometry={nodes.node_a24b4965_6852_41ba_b37a_60e5ba245102_mesh0001.geometry} material={nodes.node_a24b4965_6852_41ba_b37a_60e5ba245102_mesh0001.material} position={[13.949, 10.304, 0.177]} rotation={[Math.PI / 2, 0, 0]} scale={0.441} />
        <mesh name="Teacher_Woman_Teacher_0002" geometry={nodes.Teacher_Woman_Teacher_0002.geometry} material={materials.Teacher} position={[15.679, 4.882, 2.183]} rotation={[-3.009, -0.854, -3.02]} scale={0.948} />
        <mesh name="node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0002" geometry={nodes.node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0002.geometry} material={materials['Material.018']} position={[13.949, 7.69, 0.177]} rotation={[Math.PI / 2, 0, 0]} scale={-0.013} />
        <mesh name="node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0003" geometry={nodes.node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0003.geometry} material={materials['Material.018']} position={[13.949, 7.69, 0.177]} rotation={[Math.PI / 2, 0, 0]} scale={0.441} />
        <mesh name="node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0004" geometry={nodes.node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0004.geometry} material={materials['Material.019']} position={[13.949, 7.69, 0.177]} rotation={[Math.PI / 2, 0, 0]} scale={0.44} />
        <mesh name="node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0005" geometry={nodes.node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0005.geometry} material={materials['Material.017']} position={[13.949, 7.69, 0.177]} rotation={[Math.PI / 2, 0, 0]} scale={0.444} />
        <mesh name="node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0006" geometry={nodes.node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0006.geometry} material={materials['Material.017']} position={[13.949, 7.69, 0.177]} rotation={[Math.PI / 2, 0, 0]} scale={0.009} />
        <mesh name="node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0007" geometry={nodes.node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0007.geometry} material={materials['Material.018']} position={[13.949, 7.69, 0.177]} rotation={[Math.PI / 2, 0, 0]} scale={0.011} />
        <mesh name="node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0008" geometry={nodes.node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0008.geometry} material={materials['Material.017']} position={[13.949, 7.69, 0.177]} rotation={[Math.PI / 2, 0, 0]} scale={0.011} />
        <mesh name="node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0009" geometry={nodes.node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0009.geometry} material={materials['Material.017']} position={[13.949, 7.69, 0.177]} rotation={[Math.PI / 2, 0, 0]} scale={0.438} />
        <mesh name="node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0010" geometry={nodes.node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0010.geometry} material={materials['Material.017']} position={[13.949, 7.69, 0.177]} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
        <mesh name="node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0011" geometry={nodes.node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0011.geometry} material={materials['Material.017']} position={[13.949, 7.69, 0.177]} rotation={[Math.PI / 2, 0, 0]} scale={0.439} />
        <mesh name="node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0013" geometry={nodes.node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0013.geometry} material={materials['Material.019']} position={[13.949, 7.69, 0.177]} rotation={[Math.PI / 2, 0, 0]} scale={0.375} />
        <mesh name="node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0014" geometry={nodes.node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0014.geometry} material={materials['Material.019']} position={[13.949, 7.69, 0.177]} rotation={[Math.PI / 2, 0, 0]} scale={0.437} />
        <mesh name="node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0015" geometry={nodes.node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0015.geometry} material={materials['Material.017']} position={[13.949, 7.69, 0.177]} rotation={[Math.PI / 2, 0, 0]} scale={0.011} />
      </group>
    </group>
  )
}

useGLTF.preload('/SetWebScene.glb')
