/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Web1.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/Web1.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" position={[0.053, 2.653, -0.011]} />
        <group name="Empty002" position={[-1.216, 2.797, 4.635]} />
        <group name="Armature001" position={[1.451, 2.701, 1.198]} rotation={[0, 0.594, 0]} scale={0.219}>
          <primitive object={nodes.Bone_1} />
          <primitive object={nodes.Bone007_1} />
          <primitive object={nodes.Bone008_1} />
          <skinnedMesh name="Retopo_Sphere001" geometry={nodes.Retopo_Sphere001.geometry} material={nodes.Retopo_Sphere001.material} skeleton={nodes.Retopo_Sphere001.skeleton}>
            <group name="Empty005" position={[0.606, -0.576, 0.21]} scale={1.043} />
            <group name="Empty006" position={[-0.672, -0.557, 0.358]} scale={0.834} />
          </skinnedMesh>
        </group>
        <group name="Armature004" position={[1.588, 2.425, -1.01]} rotation={[-1.409, 0.072, 1.028]} scale={0.219}>
          <primitive object={nodes.Bone_2} />
          <primitive object={nodes.Bone007_2} />
          <primitive object={nodes.Bone008_2} />
          <skinnedMesh name="Retopo_Sphere004" geometry={nodes.Retopo_Sphere004.geometry} material={nodes.Retopo_Sphere004.material} skeleton={nodes.Retopo_Sphere004.skeleton}>
            <group name="Empty001" position={[-0.535, 1.454, 1.297]} rotation={[0, 0.223, 0]} scale={1.043} />
            <group name="Empty003" position={[-0.084, 1.321, 1.145]} rotation={[0, 0.223, 0]} scale={0.834} />
          </skinnedMesh>
        </group>
        <PerspectiveCamera name="Camera001" makeDefault={false} far={1000} near={0.1} fov={22.895} position={[8.606, 11.477, 16.792]} rotation={[-0.533, 0.238, 0.096]} />
        <mesh name="Cube013" geometry={nodes.Cube013.geometry} material={materials['Material.012']} position={[-1.772, 2.339, 1.155]} rotation={[0, -0.155, 0]}>
          <mesh name="LAPTOP001" geometry={nodes.LAPTOP001.geometry} material={materials.BASE_LAPTOP_MAT} position={[0.115, 0.401, 0.194]} rotation={[3.049, 0.289, -2.993]} scale={[-0.167, -0.014, -0.107]}>
            <mesh name="KEYBOARD001" geometry={nodes.KEYBOARD001.geometry} material={materials.KEYBOARD} position={[-0.549, -1.002, -0.666]} rotation={[Math.PI, 0, Math.PI]} scale={[-1.486, -17.229, -2.318]} />
            <group name="SCREEN_LAPTOP001" position={[0, -9.434, -1.064]} rotation={[-1.575, 0, 0]} scale={[1, 0.135, 7.433]}>
              <mesh name="Cube053" geometry={nodes.Cube053.geometry} material={materials.KEYBOARD} />
              <mesh name="Cube053_1" geometry={nodes.Cube053_1.geometry} material={materials.CODE_SCREEN_MAT} />
            </group>
          </mesh>
          <group name="Armature002" position={[0.056, 0.341, 0.413]} rotation={[-2.827, 0.362, -3.04]} scale={0.226}>
            <primitive object={nodes.Bone} />
            <primitive object={nodes.Bone007} />
            <primitive object={nodes.Bone008} />
            <skinnedMesh name="Retopo_Sphere002" geometry={nodes.Retopo_Sphere002.geometry} material={nodes.Retopo_Sphere002.material} skeleton={nodes.Retopo_Sphere002.skeleton}>
              <group name="Empty007" position={[0.165, 0.102, 1.263]} scale={1.043} />
              <group name="Empty008" position={[-0.063, 0.244, 1.206]} scale={0.834} />
            </skinnedMesh>
          </group>
          <mesh name="Cube014" geometry={nodes.Cube014.geometry} material={materials['Material.012']} position={[0.077, 0.2, -0.273]} scale={[0.301, 0.123, 0.253]} />
          <mesh name="Cube015_1" geometry={nodes.Cube015_1.geometry} material={materials['Material.012']} position={[0.077, 0.2, 0.257]} scale={[0.301, 0.123, 0.253]} />
          <mesh name="Cube016" geometry={nodes.Cube016.geometry} material={nodes.Cube016.material} position={[0.216, -0.027, -0.521]} rotation={[0.177, 0.012, 0.134]} scale={[0.018, 0.057, 0.018]} />
        </mesh>
        <mesh name="Cube026" geometry={nodes.Cube026.geometry} material={materials['Material.007']} position={[-0.767, 2.394, 1.39]} rotation={[-Math.PI, 0.391, -Math.PI]} scale={[0.649, 0.324, 0.735]} />
        <mesh name="Cube033" geometry={nodes.Cube033.geometry} material={materials['Material.002']} position={[0.939, 2.132, 1.019]} rotation={[0, -0.171, 0]} scale={[0.22, 0.176, 0.22]} />
        <mesh name="Cube034" geometry={nodes.Cube034.geometry} material={materials['Material.004']} position={[0.939, 2.34, 1.019]} rotation={[0, -0.171, 0]} scale={0.939} />
        <mesh name="Cube035" geometry={nodes.Cube035.geometry} material={materials['Material.002']} position={[0.634, 2.132, 1.789]} rotation={[0, 0.625, 0]} scale={0.939} />
        <mesh name="Cube036" geometry={nodes.Cube036.geometry} material={materials['Material.013']} position={[0.634, 2.34, 1.789]} rotation={[0, 0.625, 0]} scale={0.939} />
        <mesh name="Cylinder014" geometry={nodes.Cylinder014.geometry} material={nodes.Cylinder014.material} position={[-1.566, 2.807, -1.123]} rotation={[-2.972, 0.405, -0.126]} scale={[0.149, 0.441, 0.149]} />
        <mesh name="Cylinder015" geometry={nodes.Cylinder015.geometry} material={nodes.Cylinder015.material} position={[-0.783, 2.648, -0.136]} rotation={[-3.035, 0.322, 0.017]} scale={[0.149, 0.441, 0.149]} />
        <mesh name="Cube023" geometry={nodes.Cube023.geometry} material={nodes.Cube023.material} position={[0.965, 1.705, 1.245]} rotation={[0, -0.683, 0]} scale={0.734} />
        <mesh name="Cube025" geometry={nodes.Cube025.geometry} material={materials['Material.014']} position={[1.204, 1.706, 1.44]} rotation={[0, -0.683, 0]} scale={[0.353, 0.734, 0.734]} />
        <mesh name="Cube018" geometry={nodes.Cube018.geometry} material={materials['Material.002']} position={[-1.321, 2.034, 0.979]} />
        <mesh name="Cube020" geometry={nodes.Cube020.geometry} material={materials['Material.001']} position={[-0.011, 0.059, 0.608]} scale={1.042} />
        <mesh name="Cylinder004" geometry={nodes.Cylinder004.geometry} material={materials['Material.013']} position={[-1.306, 2.278, 1.275]} rotation={[Math.PI, -1.462, Math.PI]} scale={[0.408, 0.005, 0.408]} />
        <mesh name="Cube027" geometry={nodes.Cube027.geometry} material={nodes.Cube027.material} position={[1.803, 2.767, 0.972]} rotation={[0, 0.723, -0.205]} scale={0.803}>
          <mesh name="Cylinder005" geometry={nodes.Cylinder005.geometry} material={nodes.Cylinder005.material} position={[0.07, -0.534, -0.167]} rotation={[-1.735, 1.532, -1.233]} scale={[0.021, 0.453, 0.021]} />
          <mesh name="Cylinder006_1" geometry={nodes.Cylinder006_1.geometry} material={nodes.Cylinder006_1.material} position={[0.043, -0.098, -0.004]} rotation={[-1.735, 1.532, 0.154]} scale={[0.027, 0.292, 0.027]} />
          <mesh name="Cylinder007" geometry={nodes.Cylinder007.geometry} material={nodes.Cylinder007.material} position={[0.229, -0.492, -0.005]} rotation={[-0.01, 0.006, 0.48]} scale={[0.021, 0.454, 0.02]} />
        </mesh>
        <group name="Cube032" position={[1.178, 2.448, -1.219]} rotation={[Math.PI, -1.025, Math.PI]} scale={[0.65, 0.719, 0.65]}>
          <mesh name="Cube037" geometry={nodes.Cube037.geometry} material={materials.Material} />
          <mesh name="Cube037_1" geometry={nodes.Cube037_1.geometry} material={materials['Material.003']} />
          <mesh name="Cube037_2" geometry={nodes.Cube037_2.geometry} material={materials['Material.005']} />
          <mesh name="Cube037_3" geometry={nodes.Cube037_3.geometry} material={materials['Material.012']} />
          <mesh name="Cube037_4" geometry={nodes.Cube037_4.geometry} material={materials['Material.004']} />
          <group name="Cylinder010" position={[0.371, 0.571, -0.046]} rotation={[1.522, 1.116, -1.516]} scale={[0.045, 0.014, 0.045]}>
            <mesh name="Cylinder015_1" geometry={nodes.Cylinder015_1.geometry} material={materials['Material.004']} />
            <mesh name="Cylinder015_2" geometry={nodes.Cylinder015_2.geometry} material={materials['Material.012']} />
          </group>
          <group name="Cylinder011" position={[0.334, 0.587, -0.168]} rotation={[1.522, 1.116, -1.516]} scale={[0.045, 0.014, 0.045]}>
            <mesh name="Cylinder016" geometry={nodes.Cylinder016.geometry} material={materials['Material.004']} />
            <mesh name="Cylinder016_1" geometry={nodes.Cylinder016_1.geometry} material={materials['Material.012']} />
          </group>
          <group name="Sphere008" position={[0.398, 0.668, 0.139]} rotation={[0, 1.547, 0]} scale={0.04}>
            <mesh name="Sphere008_1" geometry={nodes.Sphere008_1.geometry} material={materials['Material.004']} />
            <mesh name="Sphere008_2" geometry={nodes.Sphere008_2.geometry} material={materials['Material.012']} />
          </group>
        </group>
        <mesh name="Sphere" geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} position={[1.383, 2.083, 1.773]} scale={0.2} />
        <mesh name="Cone" geometry={nodes.Cone.geometry} material={nodes.Cone.material} position={[1.82, 2.159, 1.961]} rotation={[0, 0.206, 0]} scale={[0.209, 0.165, 0.209]} />
        <mesh name="Cube038" geometry={nodes.Cube038.geometry} material={materials['Material.007']} position={[-0.928, 2.907, -0.743]} rotation={[0, 0.301, 0]} scale={[1.177, 1.067, 0.777]} />
        <mesh name="Cylinder017" geometry={nodes.Cylinder017.geometry} material={materials['Material.013']} position={[0.549, 2.032, 1.841]} rotation={[0, -0.683, 0]} scale={[0.552, 0.006, 0.552]} />
        <group name="Cube039" position={[1.412, 2.517, -1.153]} rotation={[Math.PI, -1.025, Math.PI]} scale={[1.126, 1.126, 1.983]}>
          <mesh name="Cube054" geometry={nodes.Cube054.geometry} material={materials['Material.006']} />
          <mesh name="Cube054_1" geometry={nodes.Cube054_1.geometry} material={materials['Material.012']} />
        </group>
        <group name="Cube040" position={[1.169, 2.243, -0.679]} rotation={[Math.PI / 2, 0, 1.835]} scale={[1.126, 1.126, 1.983]}>
          <mesh name="Cube055" geometry={nodes.Cube055.geometry} material={materials.Material} />
          <mesh name="Cube055_1" geometry={nodes.Cube055_1.geometry} material={materials['Material.012']} />
        </group>
        <mesh name="LAPTOP002" geometry={nodes.LAPTOP002.geometry} material={materials.BASE_LAPTOP_MAT} position={[-1.436, 2.883, -0.71]} rotation={[0, 0.357, 0]} scale={[-0.164, -0.014, -0.105]}>
          <group name="SCREEN_LAPTOP002" position={[0, -9.434, -1.064]} rotation={[-1.575, 0, 0]} scale={[1, 0.135, 7.433]}>
            <mesh name="Cube057" geometry={nodes.Cube057.geometry} material={materials.KEYBOARD} />
            <mesh name="Cube057_1" geometry={nodes.Cube057_1.geometry} material={materials.CODE_SCREEN_MAT} />
          </group>
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/Web1.glb')
