/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/multiusercollabnew.glb
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function MultiUserCollab(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('./models/multiusercollabnew.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  console.log("🚀 ~ MultiUserCollab ~ animations:", animations)
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  
  useEffect(() => {
    if (actions) {
      Object.values(actions).forEach(action => action.play());
    }
  }, [actions]);
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="People" position={[0, 0, 0]}>
          <group name="Object" position={[5.1, 0.78, -0.69]} scale={0}>
            <group name="SimpleTowerBricks">
              <mesh name="SimpleTowerBricks_1" geometry={nodes.SimpleTowerBricks_1.geometry} material={materials.Opaque_Mat} />
            </group>
          </group>
          <group name="Object2" position={[-0.1, 0, 0.66]}>
            <group name="SmallSquareTower">
              <mesh name="SmallSquareTower_1" geometry={nodes.SmallSquareTower_1.geometry} material={materials.Opaque_Mat} />
            </group>
          </group>
          <group name="Object3" position={[-0.39, 0, -0.4]}>
            <group name="RockSmall2_1">
              <mesh name="RockSmall2_2" geometry={nodes.RockSmall2_2.geometry} material={materials.StonesGrey} />
            </group>
          </group>
          <group name="Object4" position={[5.203, 0.705, 2.44]} rotation={[0, -Math.PI / 2, 0]}>
            <group name="Unicorn_01_" rotation={[0, -Math.PI / 2, 0]} scale={2.246}>
              <group name="Unicorn_01_Cube_028_Cube_030">
                <mesh name="Unicorn_01_Cube_028_Cube_030_primitive0_1" geometry={nodes.Unicorn_01_Cube_028_Cube_030_primitive0_1.geometry} material={materials.F06292} />
                <mesh name="Unicorn_01_Cube_028_Cube_030_primitive1" geometry={nodes.Unicorn_01_Cube_028_Cube_030_primitive1.geometry} material={materials.FFFFFF} />
                <mesh name="Unicorn_01_Cube_028_Cube_030_primitive2" geometry={nodes.Unicorn_01_Cube_028_Cube_030_primitive2.geometry} material={materials._1A1A1A} />
                <mesh name="Unicorn_01_Cube_028_Cube_030_primitive3_1" geometry={nodes.Unicorn_01_Cube_028_Cube_030_primitive3_1.geometry} material={materials.FF9800} />
              </group>
            </group>
          </group>
          <group name="Object5" position={[5.203, 0.737, 1.776]} rotation={[0, -Math.PI / 2, 0]} scale={2.273}>
            <group name="Dragon_01_(1)">
              <group name="Dragon_01_Cube_026">
                <mesh name="Dragon_01_Cube_026_primitive0_1" geometry={nodes.Dragon_01_Cube_026_primitive0_1.geometry} material={materials.F44336} />
                <mesh name="Dragon_01_Cube_026_primitive1_1" geometry={nodes.Dragon_01_Cube_026_primitive1_1.geometry} material={materials._009688} />
                <mesh name="Dragon_01_Cube_026_primitive2_1" geometry={nodes.Dragon_01_Cube_026_primitive2_1.geometry} material={materials._1A1A1A} />
                <mesh name="Dragon_01_Cube_026_primitive3_1" geometry={nodes.Dragon_01_Cube_026_primitive3_1.geometry} material={materials.FFFFFF} />
              </group>
            </group>
          </group>
        </group>
        <group name="Body_1" position={[1.781, 4.814, 2.182]} rotation={[-Math.PI, -0.698, -Math.PI]}>
          <mesh name="Head_1" geometry={nodes.Head_1.geometry} material={materials['PersonGradient-MulriUserEvent']} position={[0, 0.304, 0]} />
          <mesh name="ArmRight_1" geometry={nodes.ArmRight_1.geometry} material={materials['PersonGradient-MulriUserEvent']} position={[-0.061, 0.226, 0.007]} scale={1.229}>
            <group name="IconPhone" position={[0.025, -0.086, 0.276]} rotation={[-Math.PI, 0.347, -Math.PI]} scale={0.814}>
              <mesh name="IconPhone_primitive0" geometry={nodes.IconPhone_primitive0.geometry} material={materials.BlockOrange} />
              <mesh name="IconPhone_primitive1" geometry={nodes.IconPhone_primitive1.geometry} material={materials['White.001']} />
              <mesh name="PhoneightAR" geometry={nodes.PhoneightAR.geometry} material={materials.ProjectorLight} position={[-0.003, 0.028, -0.009]} rotation={[-1.875, -0.108, -2.811]} scale={0.403} />
              <mesh name="PhoneightFace" geometry={nodes.PhoneightFace.geometry} material={materials['ProjectorLight Variant']} position={[0, -0.001, 0]} rotation={[1.261, 0.11, 2.812]} scale={[0.335, 0.108, 0.687]} />
            </group>
          </mesh>
          <mesh name="ArmLeft_1" geometry={nodes.ArmLeft_1.geometry} material={materials['PersonGradient-MulriUserEvent']} position={[0.069, 0.226, -0.003]} scale={1.229} />
        </group>
        <group name="Body_2" position={[-2.398, 4.814, -0.873]} rotation={[0, 0.89, 0]}>
          <group name="Communication_1" position={[0, 0.756, 0]}>
            <mesh name="IconSpeech" geometry={nodes.IconSpeech.geometry} material={materials.SpeechMat} position={[0.115, 0.318, 0]} rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <mesh name="Head_2" geometry={nodes.Head_2.geometry} material={materials['PersonGradient-MulriUserEvent']} position={[0, 0.304, 0]}>
            <mesh name="IconHMD" geometry={nodes.IconHMD.geometry} material={materials['BlockRed.001']} position={[0, 0.203, 0.192]} />
          </mesh>
          <mesh name="ArmRight_2" geometry={nodes.ArmRight_2.geometry} material={materials['PersonGradient-MulriUserEvent']} position={[-0.061, 0.226, 0.007]} scale={1.229}>
            <mesh name="IconVRController_R" geometry={nodes.IconVRController_R.geometry} material={materials['BlockRed.001']} position={[-0.032, -0.18, 0.272]} rotation={[0.453, 0, 0]} scale={0.814} />
          </mesh>
          <mesh name="ArmLeft_2" geometry={nodes.ArmLeft_2.geometry} material={materials['PersonGradient-MulriUserEvent']} position={[0.069, 0.226, -0.003]} scale={1.229}>
            <mesh name="IconVRController_L" geometry={nodes.IconVRController_L.geometry} material={materials['BlockRed.001']} position={[0.032, -0.18, 0.28]} rotation={[0.453, 0, 0]} scale={0.814} />
          </mesh>
        </group>
        <group name="LittleGuards" position={[2.238, 4.486, -1.124]}>
          <group name="Unicorn" position={[-0.472, 0.012, -0.9]} rotation={[0, -0.065, 0]} scale={0.001}>
            <group name="Unicorn_1">
              <group name="Unicorn_01_Cube_028_Cube_030_1">
                <mesh name="Unicorn_01_Cube_028_Cube_030_primitive0_2" geometry={nodes.Unicorn_01_Cube_028_Cube_030_primitive0_2.geometry} material={materials.F06292} />
                <mesh name="Unicorn_01_Cube_028_Cube_030_primitive1_1" geometry={nodes.Unicorn_01_Cube_028_Cube_030_primitive1_1.geometry} material={materials.FFFFFF} />
                <mesh name="Unicorn_01_Cube_028_Cube_030_primitive2_1" geometry={nodes.Unicorn_01_Cube_028_Cube_030_primitive2_1.geometry} material={materials._1A1A1A} />
                <mesh name="Unicorn_01_Cube_028_Cube_030_primitive3_2" geometry={nodes.Unicorn_01_Cube_028_Cube_030_primitive3_2.geometry} material={materials.FF9800} />
              </group>
            </group>
          </group>
          <group name="Dragon" position={[0.334, 0.712, -0.033]} rotation={[Math.PI, -1.218, Math.PI]} scale={0.001}>
            <group name="Dragon_1">
              <group name="Dragon_01_Cube_026_1">
                <mesh name="Dragon_01_Cube_026_primitive0_2" geometry={nodes.Dragon_01_Cube_026_primitive0_2.geometry} material={materials.F44336} />
                <mesh name="Dragon_01_Cube_026_primitive1_2" geometry={nodes.Dragon_01_Cube_026_primitive1_2.geometry} material={materials._009688} />
                <mesh name="Dragon_01_Cube_026_primitive2_2" geometry={nodes.Dragon_01_Cube_026_primitive2_2.geometry} material={materials._1A1A1A} />
                <mesh name="Dragon_01_Cube_026_primitive3_2" geometry={nodes.Dragon_01_Cube_026_primitive3_2.geometry} material={materials.FFFFFF} />
              </group>
            </group>
          </group>
        </group>
        <PerspectiveCamera name="View" makeDefault={false} far={1000.134} near={0.3} fov={40} position={[-7.138, 9.777, 3.95]} rotation={[-0.937, -0.903, -0.818]} />
        <directionalLight intensity={3.142} decay={2} position={[0, 4.03, 0]} scale={0} target={nodes.Directional_Light.target}>
          <primitive object={nodes.Directional_Light.target} position={[0, 0, -1]} />
        </directionalLight>
        <directionalLight intensity={1.571} decay={2} position={[0, 4.03, 0]} scale={0} target={nodes.Directional_Light_Fill.target}>
          <primitive object={nodes.Directional_Light_Fill.target} position={[0, 0, -1]} />
        </directionalLight>
        <mesh name="GroundGrass" geometry={nodes.GroundGrass.geometry} material={materials.Opaque_Mat} position={[0, 3.599, 0]} />
        <mesh name="GroundCubeCurve" geometry={nodes.GroundCubeCurve.geometry} material={materials.Ground_MultiUserCollab_Mat} position={[0, 3.599, 0]} />
        <mesh name="GlassBenchSmall" geometry={nodes.GlassBenchSmall.geometry} material={materials.Glass_Mat} position={[0.211, 4.609, -3.964]} />
        <mesh name="RockSmall2" geometry={nodes.RockSmall2.geometry} material={materials.StonesGrey} position={[0.63, 4.609, -3.837]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.996} />
        <mesh name="Dragon_01_Cube_026_primitive0" geometry={nodes.Dragon_01_Cube_026_primitive0.geometry} material={materials.F44336} position={[5.203, 4.767, 1.776]} rotation={[0, -Math.PI / 2, 0]} scale={2.273} />
        <mesh name="Dragon_01_Cube_026_primitive1" geometry={nodes.Dragon_01_Cube_026_primitive1.geometry} material={materials._009688} position={[5.203, 4.767, 1.776]} rotation={[0, -Math.PI / 2, 0]} scale={2.273} />
        <mesh name="Dragon_01_Cube_026_primitive2" geometry={nodes.Dragon_01_Cube_026_primitive2.geometry} material={materials._1A1A1A} position={[5.203, 4.767, 1.776]} rotation={[0, -Math.PI / 2, 0]} scale={2.273} />
        <mesh name="Dragon_01_Cube_026_primitive3" geometry={nodes.Dragon_01_Cube_026_primitive3.geometry} material={materials.FFFFFF} position={[5.203, 4.767, 1.776]} rotation={[0, -Math.PI / 2, 0]} scale={2.273} />
        <mesh name="Unicorn_01_Cube_028_Cube_030_primitive0" geometry={nodes.Unicorn_01_Cube_028_Cube_030_primitive0.geometry} material={materials.F06292} position={[5.203, 4.735, 2.44]} rotation={[0, -Math.PI / 2, 0]} scale={2.246} />
        <mesh name="Unicorn_01_Cube_028_Cube_030_primitive3" geometry={nodes.Unicorn_01_Cube_028_Cube_030_primitive3.geometry} material={materials.FF9800} position={[5.203, 4.735, 2.44]} rotation={[0, -Math.PI / 2, 0]} scale={2.246} />
        <mesh name="Body" geometry={nodes.Body.geometry} material={materials['PersonGradient-MulriUserEvent']} position={[-2.28, 4.814, 0.82]} rotation={[-Math.PI, 1.354, -Math.PI]}>
          <mesh name="ArmLeft" geometry={nodes.ArmLeft.geometry} material={materials['PersonGradient-MulriUserEvent']} position={[0.069, 0.226, -0.003]} scale={1.229}>
            <mesh name="IconVRController_L_1" geometry={nodes.IconVRController_L_1.geometry} material={materials['BlockRed.001']} position={[0.032, -0.18, 0.28]} rotation={[0.453, 0, 0]} scale={0.814} />
          </mesh>
          <mesh name="ArmRight" geometry={nodes.ArmRight.geometry} material={materials['PersonGradient-MulriUserEvent']} position={[-0.061, 0.226, 0.007]} scale={1.229}>
            <mesh name="IconVRController_R_1" geometry={nodes.IconVRController_R_1.geometry} material={materials['BlockRed.001']} position={[-0.032, -0.18, 0.272]} rotation={[0.453, 0, 0]} scale={0.814} />
          </mesh>
          <group name="Communication" position={[0, 0.756, 0]}>
            <mesh name="IconSpeech_1" geometry={nodes.IconSpeech_1.geometry} material={materials.SpeechMat} position={[0.115, 0.318, 0]} rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <mesh name="Head" geometry={nodes.Head.geometry} material={materials['PersonGradient-MulriUserEvent']} position={[0, 0.304, 0]}>
            <mesh name="IconHMD_1" geometry={nodes.IconHMD_1.geometry} material={materials['BlockRed.001']} position={[0, 0.203, 0.192]} />
          </mesh>
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('./models/multiusercollabnew.glb')
