/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/website.glb 
Needle: [object Object]
*/

import React from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Website(props) {
  const { nodes, materials } = useGLTF('./models/website.glb')
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera makeDefault={true} far={49.997} near={0.02} fov={45} position={[-6.089, 8.557, 7.7]} rotation={[-0.789, -0.508, -0.456]} />
      <PerspectiveCamera makeDefault={true} far={1000.134} near={0.3} fov={60} rotation={[-Math.PI, 0, -Math.PI]} />
    </group>
  )
}

useGLTF.preload('./models/website.glb')
