/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/animals.glb 
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Animals(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('./models/animals.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    if (actions.Eating) {
      const action = actions.Eating
      action.play()
    }
  }, [actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="AnimalArmature" position={[-2.067, 4.056, 0.96]} rotation={[0, -0.191, 0]} scale={0.355}>
          <primitive object={nodes.Body} />
          <primitive object={nodes.IKBackLegL} />
          <primitive object={nodes.IKFrontLegL} />
          <primitive object={nodes.IKBackLegR} />
          <primitive object={nodes.IKFrontLegR} />
          <group name="Alpaca">
            <skinnedMesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials.Main} skeleton={nodes.Cube001.skeleton} />
            <skinnedMesh name="Cube001_1" geometry={nodes.Cube001_1.geometry} material={materials.Main_Light} skeleton={nodes.Cube001_1.skeleton} />
            <skinnedMesh name="Cube001_2" geometry={nodes.Cube001_2.geometry} material={materials.Hooves} skeleton={nodes.Cube001_2.skeleton} />
            <skinnedMesh name="Cube001_3" geometry={nodes.Cube001_3.geometry} material={materials.Main_Dark} skeleton={nodes.Cube001_3.skeleton} />
            <skinnedMesh name="Cube001_4" geometry={nodes.Cube001_4.geometry} material={materials.Muzzle} skeleton={nodes.Cube001_4.skeleton} />
            <skinnedMesh name="Cube001_5" geometry={nodes.Cube001_5.geometry} material={materials.Eyes_Black} skeleton={nodes.Cube001_5.skeleton} />
            <skinnedMesh name="Cube001_6" geometry={nodes.Cube001_6.geometry} material={materials.Eyes_White} skeleton={nodes.Cube001_6.skeleton} />
          </group>
        </group>
        <group name="AnimalArmature001" position={[1.31, 4.041, -0.466]} rotation={[0, 0.621, 0]} scale={0.36}>
          <primitive object={nodes.Body_1} />
          <primitive object={nodes.IKBackLegL_1} />
          <primitive object={nodes.IKFrontLegL_1} />
          <primitive object={nodes.IKBackLegR_1} />
          <primitive object={nodes.IKFrontLegR_1} />
          <group name="Stag">
            <skinnedMesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials['Material.001']} skeleton={nodes.Cube002.skeleton} />
            <skinnedMesh name="Cube002_1" geometry={nodes.Cube002_1.geometry} material={materials['Material.002']} skeleton={nodes.Cube002_1.skeleton} />
            <skinnedMesh name="Cube002_2" geometry={nodes.Cube002_2.geometry} material={materials['Material.003']} skeleton={nodes.Cube002_2.skeleton} />
            <skinnedMesh name="Cube002_3" geometry={nodes.Cube002_3.geometry} material={materials['Material.010']} skeleton={nodes.Cube002_3.skeleton} />
            <skinnedMesh name="Cube002_4" geometry={nodes.Cube002_4.geometry} material={materials['Material.011']} skeleton={nodes.Cube002_4.skeleton} />
          </group>
        </group>
        <group name="FileSize">
          <group name="RoomBase" position={[0, 4.03, 0]}>
            <group name="GroundCubeQuad001" position={[0, -0.431, 0]}>
              <group name="GroundLayerSize001" />
            </group>
            <group name="SceneLoader" />
            <group name="Songs" scale={4}>
              <group name="OldMacDonald">
                <group name="OldMacDonald_Website" />
              </group>
              <group name="TrongCom">
                <group name="TrongCom_Website" position={[0, 0.003, 0]} />
              </group>
            </group>
          </group>
        </group>
        <mesh name="GroundCubeQuad002" geometry={nodes.GroundCubeQuad002.geometry} material={materials['Ground_FileSize_Mat.002']} position={[0, 3.599, -0.13]} scale={[1.2, 1, 0.792]} />
        <mesh name="GroundLayerSize002" geometry={nodes.GroundLayerSize002.geometry} material={materials['Opaque_Mat.002']} position={[0, 3.599, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/animals.glb')
