/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/OldMacDonald.glb 
Needle: [object Object]
*/

import React, { useMemo, useRef } from 'react'
import { useGraph } from '@react-three/fiber'
import { useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Character2({ scene, animations, config, ...props }) {
  const group = useRef()
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  return (
    <group ref={group} {...props} dispose={null} scale={config.scale} position={[4,1,0]}>
      <group name="OldMacDonald_Websiteglb">
        <group name="OldMacDonald_Website">
          <group name="Haystack_(1)" position={[0.678, 0.055, 0.055]} rotation={[-Math.PI, -0.223, -Math.PI]} scale={0.85}>
            <group name="Object" />
            <group name="Interaction" />
            <group name="VocablePosition" position={[0.004, 0.067, -0.018]} />
          </group>
          <group name="Kuh" position={[0.066, 0, 0.053]} rotation={[0, -0.009, 0]} scale={2.2}>
            <group name="Object_1">
              <group name="Kuh_T-Pose" scale={1.136}>
                <group name="IK_L_Hand" position={[0.029, 0.066, 0.017]} />
                <group name="IK_L_Leg" position={[0.012, 0.004, 0]} />
                <group name="IK_R_Hand" position={[-0.019, 0.041, 0.003]} />
                <group name="IK_R_Leg" position={[-0.013, 0.004, 0]} />
                <group name="IK_Tail" position={[0.004, 0.037, -0.017]} />
                <primitive object={nodes.mixamorigHips} />
                <group name="R_Elbow_CTRL" position={[-0.024, 0.057, -0.018]} />
                <group name="L_Elbow_CTRL_7" position={[0.021, 0.058, -0.018]} />
                <group name="L_Knee_CTRL_1" position={[0.009, 0.02, 0.015]} />
                <group name="R_Knee_CTRL_1" position={[-0.009, 0.02, 0.015]} />
                <skinnedMesh name="Kuh_1" geometry={nodes.Kuh_1.geometry} material={materials.Kuh_Mat} skeleton={nodes.Kuh_1.skeleton} />
              </group>
              <group name="Kuh_Play_Kontrabass">
                <group name="IK_L_Hand_1" position={[0.028, 0.073, 0.017]} />
                <group name="IK_L_Leg_1" position={[0.012, 0.004, 0]} />
                <group name="IK_R_Hand_1" position={[-0.019, 0.042, 0.003]} />
                <group name="IK_R_Leg_1" position={[-0.013, 0.004, 0]} />
                <group name="IK_Tail_1" position={[0.004, 0.037, -0.017]} />
                <primitive object={nodes.mixamorigHips_1} />
                <group name="R_Elbow_CTRL_1" position={[-0.024, 0.057, -0.018]} />
                <group name="IK_Kontrabas" position={[0.008, 0, 0.029]} />
                <group name="L_Elbow_CTRL_8" position={[0.023, 0.057, -0.018]} />
                <group name="L_Knee_CTRL_2" position={[0.007, 0.019, 0.015]} />
                <group name="R_Knee_CTRL_2" position={[-0.007, 0.019, 0.015]} />
                <skinnedMesh name="Kontrabass05" geometry={nodes.Kontrabass05.geometry} material={materials.Kontrabass_Mat} skeleton={nodes.Kontrabass05.skeleton} position={[0.008, 0, -0.004]} rotation={[-0.396, -0.417, -0.171]}>
                  <group name="VocablePosition_15" position={[0.025, 0.102, 0.034]} />
                </skinnedMesh>
                <skinnedMesh name="Kontrabassbogen1" geometry={nodes.Kontrabassbogen1.geometry} material={materials.Kontrabass_Mat} skeleton={nodes.Kontrabassbogen1.skeleton} position={[0.001, -0.015, -0.024]} rotation={[2.519, 0.182, -1.248]} />
              </group>
            </group>
            <group name="Interaction_1" />
            <group name="CharacterAudioSource" />
            <group name="Notes" position={[0, 0.064, 0]} />
            <group name="LookAt" position={[0.21, 1.062, -0.174]} rotation={[0, -0.855, 0]} scale={8.894} />
            <group name="VocablePosition_1" position={[-0.004, 0.13, 0]} />
          </group>
          <group name="Schaf" position={[-0.183, 0.191, -0.086]} rotation={[0, 0.403, 0]} scale={2.25}>
            <group name="Object_2">
              <group name="Schaf_T-Pose">
                <group name="IK_L_Hand_2" position={[0.017, 0.036, 0]} />
                <group name="IK_L_Leg_2" position={[0.007, 0.004, 0.001]} />
                <group name="IK_R_Hand_2" position={[-0.021, 0.035, 0.001]} />
                <group name="IK_R_Leg_2" position={[-0.007, 0.004, 0.001]} />
                <group name="L_Elbow_CTRL" position={[0.04, 0.044, -0.013]} />
                <group name="L_knee_CTRL1" position={[0.005, 0.013, 0.015]} />
                <primitive object={nodes.mixamorigHips_2} />
                <group name="R_Elbow_CTRL_2" position={[-0.04, 0.044, -0.013]} />
                <group name="R_knee_CTRL" position={[-0.005, 0.013, 0.015]} />
                <skinnedMesh name="Schaf_1" geometry={nodes.Schaf_1.geometry} material={materials.Schaf_Mat} skeleton={nodes.Schaf_1.skeleton} />
              </group>
              <group name="Schaf_Play_Strohhalm">
                <group name="IK_L_Hand_3" position={[0.017, 0.036, 0]} />
                <group name="IK_L_Leg_3" position={[0.007, 0.004, 0.001]} />
                <group name="IK_R_Hand_3" position={[-0.021, 0.035, 0.001]} />
                <group name="IK_R_Leg_3" position={[-0.007, 0.004, 0.001]} />
                <group name="L_Elbow_CTRL_1" position={[0.04, 0.044, -0.013]} />
                <group name="L_knee_CTRL1_1" position={[0.005, 0.013, 0.015]} />
                <group name="mixamorigHips_3" position={[-0.002, 0.021, 0]} rotation={[0, 0, 0.14]}>
                  <group name="mixamorigLeftUpLeg_3" position={[0.005, -0.002, 0.001]} rotation={[-0.251, -0.004, 0.086]}>
                    <group name="mixamorigLeftLeg_3" position={[0, -0.008, 0]} rotation={[0.488, 0, 0.004]}>
                      <group name="mixamorigLeftFoot_3" position={[0, -0.009, 0]} />
                    </group>
                  </group>
                  <group name="mixamorigRightUpLeg_3" position={[-0.005, -0.002, 0.001]} rotation={[-0.555, 0.178, -0.02]}>
                    <group name="mixamorigRightLeg_3" position={[0, -0.008, 0]} rotation={[1.094, 0.004, 0.008]}>
                      <group name="mixamorigRightFoot_3" position={[0, -0.009, 0]} />
                    </group>
                  </group>
                  <group name="mixamorigSpine_1" position={[0, 0.009, 0]}>
                    <group name="mixamorigSpine1_1" position={[0, 0.009, 0]}>
                      <group name="mixamorigSpine2_1" position={[0, 0.008, 0]}>
                        <group name="mixamorigLeftShoulder_1" position={[0.003, 0.005, 0]}>
                          <group name="mixamorigLeftArm_3" position={[0.01, -0.006, 0]} rotation={[1.996, -0.741, 0.875]}>
                            <group name="mixamorigLeftForeArm_3" position={[0.006, -0.005, 0.001]} rotation={[-1.395, 0.356, 0.245]}>
                              <group name="mixamorigLeftHand_3" position={[0.007, -0.005, 0.001]} />
                            </group>
                          </group>
                        </group>
                        <group name="mixamorigNeck_3" position={[0, 0.005, 0]} rotation={[-0.246, 0.212, 0.051]}>
                          <group name="mixamorigHead_1" position={[0, 0.003, 0]}>
                            <group name="mixamorigHeadTop_End_1" position={[0, 0.036, -0.001]} />
                          </group>
                        </group>
                        <primitive object={nodes.mixamorigRightShoulder_1} />
                      </group>
                    </group>
                  </group>
                </group>
                <group name="R_Elbow_CTRL_3" position={[-0.04, 0.044, -0.013]} />
                <group name="R_knee_CTRL_1" position={[-0.005, 0.013, 0.015]} />
                <group name="IK_Stroh2" position={[-0.03, 0.054, 0.037]} />
                <skinnedMesh name="Strohhalm" geometry={nodes.Strohhalm.geometry} material={materials.Strohhalm_Mat} skeleton={nodes.Strohhalm.skeleton} position={[-0.017, 0.053, -0.009]} rotation={[-2.525, 0, -Math.PI]} />
              </group>
            </group>
            <group name="Interaction_2" />
            <group name="CharacterAudioSource_1" />
            <group name="Notes_1" position={[0, 0.064, 0]} />
            <group name="LookAt_1" position={[-0.162, 0.551, 0.339]} rotation={[0, -1.006, 0]} scale={7.827} />
            <group name="VocablePosition_2" position={[0, 0.096, 0]} />
          </group>
          <group name="Pony" position={[0.373, 0, 0.239]} rotation={[0, -0.142, 0]} scale={2.35}>
            <group name="Object_3">
              <group name="Pony_T-Pose">
                <group name="IK_L_Hand_4" position={[0.007, 0.055, 0.013]} />
                <group name="IK_L_Leg_4" position={[0.007, 0.004, -0.001]} />
                <group name="IK_R_Hand_4" position={[-0.014, 0.048, 0.014]} />
                <group name="IK_R_Leg_4" position={[-0.007, 0.004, -0.001]} />
                <group name="L_Elbow_CTRL_2" position={[0.019, 0.043, -0.018]} />
                <primitive object={nodes.mixamorigHips_4} />
                <group name="R_Elbow_CTRL_4" position={[-0.026, 0.06, -0.018]} />
                <group name="L_Knee_CTRL_3" position={[0.007, 0.013, 0.015]} />
                <group name="R_Knee_CTRL_3" position={[-0.007, 0.013, 0.015]} />
                <group name="Tail_CTRL" position={[0, 0.032, -0.041]} />
                <skinnedMesh name="Pony_1" geometry={nodes.Pony_1.geometry} material={materials.Pony_Light_Mat} skeleton={nodes.Pony_1.skeleton} />
              </group>
              <group name="Pony_Idle_Banjo">
                <group name="IK_L_Hand_5" position={[0.007, 0.055, 0.013]} />
                <group name="IK_L_Leg_5" position={[0.007, 0.004, -0.001]} />
                <group name="IK_R_Hand_5" position={[-0.014, 0.048, 0.014]} />
                <group name="IK_R_Leg_5" position={[-0.007, 0.004, -0.001]} />
                <group name="L_Elbow_CTRL_3" position={[0.019, 0.043, -0.018]} />
                <group name="mixamorigHips_5" position={[0, 0.024, 0]} rotation={[0, 0, 0.108]}>
                  <group name="mixamorigLeftUpLeg_5" position={[0.007, -0.003, 0]} rotation={[-0.432, 0.039, -0.112]}>
                    <group name="mixamorigLeftLeg_5" position={[0, -0.011, 0]} rotation={[0.957, -0.003, 0.003]}>
                      <group name="mixamorigLeftFoot_5" position={[0, -0.009, 0]} />
                    </group>
                  </group>
                  <group name="mixamorigRightUpLeg_5" position={[-0.007, -0.003, 0]} rotation={[-0.562, 0.046, -0.119]}>
                    <group name="mixamorigRightLeg_5" position={[0, -0.011, 0]} rotation={[1.273, 0, -0.012]}>
                      <group name="mixamorigRightFoot_5" position={[0, -0.009, 0]} />
                    </group>
                  </group>
                  <group name="Tail_3" position={[0, 0.004, -0.01]} rotation={[0.175, 0.014, -0.359]}>
                    <group name="Tail01_3" position={[0, -0.004, -0.007]} rotation={[-0.263, 0, 0]}>
                      <group name="Tail02_3" position={[0, -0.008, -0.003]} rotation={[0.403, 0, 0]}>
                        <group name="Tail03_1" position={[0, -0.004, -0.008]} />
                      </group>
                    </group>
                  </group>
                  <primitive object={nodes.mixamorigSpine_8} />
                </group>
                <group name="R_Elbow_CTRL_5" position={[-0.026, 0.06, -0.018]} />
                <group name="IK_Tail__not_attached_" position={[-0.005, 0.015, -0.028]} />
                <group name="L_Knee_CTRL_4" position={[0.007, 0.013, 0.015]} />
                <group name="R_Knee_CTRL_4" position={[-0.007, 0.013, 0.015]} />
                <group name="Tail_CTRL_1" position={[0, 0.032, -0.041]} />
                <skinnedMesh name="Banjo1" geometry={nodes.Banjo1.geometry} material={materials.Banjo_Mat} skeleton={nodes.Banjo1.skeleton} position={[-0.007, 0.05, 0.012]} rotation={[-0.307, -0.289, -1.043]}>
                  <group name="VocablePosition_16" position={[0, 0.037, 0.001]} />
                </skinnedMesh>
              </group>
            </group>
            <group name="Interaction_3" />
            <group name="CharacterAudioSource_2" />
            <group name="Notes_2" position={[0, 0.064, 0]} />
            <group name="LookAt_2" position={[0.241, 0.935, -0.13]} rotation={[0, -0.855, 0]} scale={7.827} />
            <group name="VocablePosition_3" position={[0, 0.099, -0.003]} />
          </group>
          <group name="Fuchs" position={[-0.329, -0.003, 0.248]} rotation={[0, 0.217, 0]} scale={2.2}>
            <group name="Object_4">
              <group name="Fuchs_T-Pose">
                <group name="IK_L_Hand_6" position={[0.017, 0.061, 0.015]} />
                <group name="IK_L_Leg_6" position={[0.009, 0.005, 0]} />
                <group name="IK_R_Hand_6" position={[-0.006, 0.05, 0.012]} />
                <group name="IK_R_Leg_6" position={[-0.009, 0.005, 0]} />
                <group name="IK_Tail_2" position={[0.011, 0.038, -0.021]} />
                <group name="L_Elbow_CTRL_4" position={[0.036, 0.02, -0.013]} />
                <group name="L_knee_CTRL1_2" position={[0.008, 0.018, 0.015]} />
                <primitive object={nodes.mixamorigHips_6} />
                <group name="R_Elbow_CTRL_6" position={[-0.019, 0.054, -0.013]} />
                <group name="R_knee_CTRL_2" position={[-0.009, 0.018, 0.015]} />
                <group name="Tail_CTRL_2" position={[0, 0.021, -0.023]} />
                <skinnedMesh name="Fuchs_1" geometry={nodes.Fuchs_1.geometry} material={materials.Fuchs_Mat} skeleton={nodes.Fuchs_1.skeleton} />
              </group>
              <group name="Fuchs_Idle_Gitarre">
                <group name="IK_L_Hand_7" position={[0.017, 0.061, 0.015]} />
                <group name="IK_L_Leg_7" position={[0.009, 0.005, 0]} />
                <group name="IK_R_Hand_7" position={[-0.006, 0.05, 0.012]} />
                <group name="IK_R_Leg_7" position={[-0.009, 0.005, 0]} />
                <group name="IK_Tail_3" position={[0.011, 0.038, -0.021]} />
                <group name="L_Elbow_CTRL_5" position={[0.036, 0.02, -0.013]} />
                <group name="L_knee_CTRL1_3" position={[0.008, 0.018, 0.015]} />
                <group name="mixamorigHips_7" position={[0.005, 0.031, 0]} rotation={[0, 0, 0.093]}>
                  <group name="mixamorigLeftUpLeg_7" position={[0.006, -0.002, 0]} rotation={[-0.404, -0.053, -0.201]}>
                    <group name="mixamorigLeftLeg_7" position={[0, -0.015, 0]} rotation={[0.821, 0.001, -0.001]}>
                      <group name="mixamorigLeftFoot_7" position={[0, -0.013, 0]} />
                    </group>
                  </group>
                  <group name="mixamorigRightUpLeg_7" position={[-0.006, -0.002, 0]} rotation={[-0.474, -0.106, -0.463]}>
                    <group name="mixamorigRightLeg_7" position={[0, -0.015, 0]} rotation={[0.825, -0.001, 0.001]}>
                      <group name="mixamorigRightFoot_7" position={[0, -0.013, 0]} />
                    </group>
                  </group>
                  <group name="mixamorigSpine_3" position={[0, 0.007, 0]} rotation={[-0.2, -0.022, -0.002]}>
                    <group name="mixamorigSpine1_4" position={[0, 0.007, 0]}>
                      <group name="mixamorigSpine2_4" position={[0, 0.007, 0]}>
                        <group name="mixamorigNeck_7" position={[0, 0.007, 0]} rotation={[-0.127, -0.075, 0.095]}>
                          <group name="mixamorigHead_4" position={[0, 0.003, 0]}>
                            <group name="mixamorigHeadTop_End_4" position={[0, 0.036, -0.001]} />
                          </group>
                        </group>
                        <group name="mixamorigLeftShoulder_4" position={[0.003, 0.005, 0]}>
                          <group name="mixamorigLeftArm_7" position={[0.005, -0.002, -0.001]} rotation={[-0.089, -0.853, 0.149]}>
                            <group name="mixamorigLeftForeArm_7" position={[0.01, -0.008, 0]} rotation={[-1.654, -0.102, -0.04]}>
                              <group name="mixamorigLeftHand_7" position={[0.011, -0.008, 0.002]} />
                            </group>
                          </group>
                        </group>
                        <group name="mixamorigRightShoulder_4" position={[-0.003, 0.005, 0]}>
                          <group name="mixamorigRightArm_7" position={[-0.005, -0.002, -0.001]} rotation={[1.37, 0.347, -1.347]}>
                            <group name="mixamorigRightForeArm_7" position={[-0.01, -0.008, 0]} rotation={[-1.876, 0.366, 0.419]}>
                              <group name="mixamorigRightHand_7" position={[-0.011, -0.008, 0.002]} />
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                    <mesh name="Gitarre" geometry={nodes.Gitarre.geometry} material={materials.Guitar_Mat} position={[-0.006, 0.007, 0.011]} rotation={[-0.297, -0.544, 0.279]} scale={0.799}>
                      <group name="VocablePosition_14" position={[0.041, 0, 0.003]} />
                    </mesh>
                  </group>
                  <group name="Tail_5" position={[0, 0.004, -0.008]} rotation={[-0.337, -0.468, -0.282]}>
                    <group name="Tail01_5" position={[0, 0, -0.009]} rotation={[0.392, 0, 0]}>
                      <group name="Tail02_5" position={[0, 0.003, -0.006]} />
                    </group>
                  </group>
                </group>
                <group name="R_Elbow_CTRL_7" position={[-0.019, 0.054, -0.013]} />
                <group name="R_knee_CTRL_3" position={[-0.009, 0.018, 0.015]} />
              </group>
            </group>
            <group name="Interaction_4" />
            <group name="CharacterAudioSource_3" />
            <group name="Notes_3" position={[0, 0.064, 0]} />
            <group name="LookAt_3" position={[0.039, 0.935, -0.17]} rotation={[0, -0.855, 0]} scale={7.827} />
            <group name="VocablePosition_4" position={[0, 0.098, 0]} />
          </group>
          <group name="Barn" position={[0.496, 0, -0.1]} rotation={[0, 1.203, 0]}>
            <group name="Object_5">
              <mesh name="Barn_1" geometry={nodes.Barn_1.geometry} material={materials.Barn_Mat} scale={1.6} />
            </group>
            <group name="Interaction_5" />
            <group name="VocablePosition_5" position={[0, 0.242, 0]} />
          </group>
          <group name="Wall" position={[0.137, 0.051, -0.401]} rotation={[0, -Math.PI / 2, 0]}>
            <group name="Object_6">
              <group name="Zaun_Mauer" scale={2}>
                <mesh name="fence" geometry={nodes.fence.geometry} material={materials.Fence} position={[-0.006, 0, -0.088]} rotation={[Math.PI, -0.273, Math.PI]}>
                  <group name="VocablePosition_11" position={[0.043, 0.022, -0.053]} />
                </mesh>
                <mesh name="wall-part1" geometry={nodes['wall-part1'].geometry} material={materials.Wall}>
                  <group name="VocablePosition_12" position={[0.049, 0.025, 0.243]} />
                </mesh>
                <mesh name="wall-part2" geometry={nodes['wall-part2'].geometry} material={materials.Wall}>
                  <group name="VocablePosition_13" />
                </mesh>
              </group>
            </group>
            <group name="Interaction_6" />
          </group>
          <group name="Haystacks" position={[0.118, -0.768, -0.324]} rotation={[0, -0.382, 0]}>
            <group name="Haystack_(2)" position={[-0.211, 0.909, 0.342]} rotation={[-Math.PI, -1.325, -Math.PI]} scale={0.85}>
              <group name="Object_7">
                <mesh name="Haystack" geometry={nodes.Haystack.geometry} material={materials.Haystack_Mat} />
              </group>
              <group name="Interaction_9" />
              <group name="VocablePosition_8" position={[0.004, 0.067, -0.018]} />
            </group>
            <group name="Haystack_(3)" position={[-0.192, 0.821, 0.388]} rotation={[0, 1.492, 0]} scale={0.85}>
              <group name="Object_8">
                <mesh name="Haystack_1" geometry={nodes.Haystack_1.geometry} material={materials.Haystack_Mat} />
              </group>
              <group name="Interaction_10" />
              <group name="VocablePosition_9" position={[0.004, 0.067, -0.018]} />
            </group>
            <group name="Haystack_(4)" position={[-0.164, 0.821, 0.288]} rotation={[0, 1.492, 0]} scale={0.85}>
              <group name="Object_9">
                <mesh name="Haystack_2" geometry={nodes.Haystack_2.geometry} material={materials.Haystack_Mat} />
              </group>
              <group name="Interaction_11" />
              <group name="VocablePosition_10" position={[0.004, 0.067, -0.018]} />
            </group>
          </group>
          <group name="Chicken_House_1" position={[-0.523, 0, 0]} rotation={[0, -1.155, 0]}>
            <group name="Object_10">
              <mesh name="Chicken_House" geometry={nodes.Chicken_House.geometry} material={materials.Chicken_House_Mat} scale={1.909} />
            </group>
            <group name="Interaction_7" />
            <group name="VocablePosition_6" position={[0, 0.131, 0]} />
          </group>
          <group name="Cow" position={[0.507, 0, -0.143]} rotation={[0, 0.156, 0]} scale={3.2}>
            <group name="Object_11">
              <group name="Wasserbueffel_T-Pose" scale={0.455}>
                <primitive object={nodes.mixamorigHips_8} />
                <group name="IK_L_Hand_8" position={[0.031, 0.048, -0.003]} />
                <group name="IK_L_Leg_8" position={[0.009, 0.005, 0]} />
                <group name="IK_R_Hand_8" position={[-0.031, 0.048, -0.003]} />
                <group name="IK_R_Leg_8" position={[-0.009, 0.005, 0]} />
                <group name="IK_Tail_4" position={[0, 0.042, -0.031]} />
                <group name="L_Elbow_CTRL_6" position={[0.033, 0.053, -0.024]} />
                <group name="L_Knee_CTRL" position={[0.009, 0.02, 0.015]} />
                <group name="R_Elbow_CTRL_8" position={[-0.021, 0.058, -0.018]} />
                <group name="R_Knee_CTRL" position={[-0.009, 0.02, 0.015]} />
                <skinnedMesh name="Wasserbueffel" geometry={nodes.Wasserbueffel.geometry} material={materials.Cow_Brown_Mat} skeleton={nodes.Wasserbueffel.skeleton} />
              </group>
            </group>
            <group name="Interaction_8" />
            <group name="CharacterAudioSource_4" />
            <group name="LookAt_4" position={[-0.025, 0.328, 0.18]} rotation={[0, 0.702, 0]} scale={5.177} />
            <group name="Notes_4" position={[0, 0.064, 0]} />
            <group name="VocablePosition_7" position={[0, 0.048, 0]} />
          </group>
          <group name="Gras">
            <group name="PlantGrass_Variant" position={[-0.423, 0, -0.486]} rotation={[Math.PI, -0.364, Math.PI]} scale={1.291}>
              <group name="Object_12">
                <mesh name="PlantQuad" geometry={nodes.PlantQuad.geometry} material={materials['PlantGrass WebsiteVariant']} position={[0, 0.04, 0]} scale={0.079} />
              </group>
              <group name="Interaction_12" />
            </group>
            <group name="PlantGrass_Variant_(4)" position={[0.328, 0, -0.225]} rotation={[-Math.PI, 0.16, -Math.PI]} scale={1.291}>
              <group name="Object_13">
                <mesh name="PlantQuad_1" geometry={nodes.PlantQuad_1.geometry} material={materials['PlantGrass WebsiteVariant']} position={[0, 0.04, 0]} scale={0.079} />
              </group>
              <group name="Interaction_13" />
            </group>
            <group name="PlantGrass_Variant_(5)" position={[-0.695, 0, 0.147]} rotation={[Math.PI, -0.17, Math.PI]} scale={1.291}>
              <group name="Object_14">
                <mesh name="PlantQuad_2" geometry={nodes.PlantQuad_2.geometry} material={materials['PlantGrass WebsiteVariant']} position={[0, 0.04, 0]} scale={0.079} />
              </group>
              <group name="Interaction_14" />
            </group>
            <group name="PlantGrass_Variant_(6)" position={[0.721, 0, 0.024]} rotation={[Math.PI, -0.17, Math.PI]} scale={1.291}>
              <group name="Object_15">
                <mesh name="PlantQuad_3" geometry={nodes.PlantQuad_3.geometry} material={materials['PlantGrass WebsiteVariant']} position={[0, 0.04, 0]} scale={0.079} />
              </group>
              <group name="Interaction_15" />
            </group>
          </group>
          <spotLight intensity={0.471} angle={Math.PI / 4} penumbra={1} decay={2} distance={1} position={[-0.202, 0.752, -0.086]} rotation={[-Math.PI / 2, 0, -Math.PI]} target={nodes.Spot_Light.target}>
            <primitive object={nodes.Spot_Light.target} position={[0, 0, -1]} />
          </spotLight>
          <mesh name="DIN-B5" geometry={nodes['DIN-B5'].geometry} material={materials['SongCard-Default']} />
        </group>
      </group>
    </group>
  )
}

