/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/officeDino.glb 
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function OfficeDino(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('./models/officeDino.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
    {/**
    useEffect(() => {
      if (actions) {
        Object.values(actions).forEach((action) => action.play())
      }
    }, [actions]) */}
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="tex">
        <group name="EmptyHead002" position={[7.379, 0.785, -0.04]} rotation={[Math.PI / 2, 0, 0]} scale={[0.011, 0.009, 0.008]} />
        <group name="EmptyGlasses006" position={[7.379, 0.785, -0.04]} rotation={[Math.PI / 2, 0, 0]} scale={[0.011, 0.009, 0.008]} />
        <group name="Character_Female_Preset_11001" position={[7.379, 0.785, -0.04]} rotation={[Math.PI / 2, 0, 0]} scale={[0.011, 0.009, 0.008]} />
        <group name="Artist02" position={[2.028, 4.211, -5.972]} rotation={[-Math.PI, 1.211, -Math.PI]} scale={0.736}>
          <group name="Armature006" rotation={[Math.PI / 2, 0, 0]} scale={0.011}>
            <primitive object={nodes.mixamorigHips} />
            <skinnedMesh name="GLASSES_02_2001" geometry={nodes.GLASSES_02_2001.geometry} material={materials['Modular_Characters.007']} skeleton={nodes.GLASSES_02_2001.skeleton} />
            <skinnedMesh name="HANDS_01_1006" geometry={nodes.HANDS_01_1006.geometry} material={materials['Modular_Characters.007']} skeleton={nodes.HANDS_01_1006.skeleton} />
            <skinnedMesh name="HAT_03_1001" geometry={nodes.HAT_03_1001.geometry} material={materials['Modular_Characters.007']} skeleton={nodes.HAT_03_1001.skeleton} />
            <skinnedMesh name="HEAD_01_3002" geometry={nodes.HEAD_01_3002.geometry} material={materials['Modular_Characters.007']} skeleton={nodes.HEAD_01_3002.skeleton} />
            <skinnedMesh name="PANTS_07_2001" geometry={nodes.PANTS_07_2001.geometry} material={materials['Modular_Characters.007']} skeleton={nodes.PANTS_07_2001.skeleton} />
            <skinnedMesh name="SHOES_06_5001" geometry={nodes.SHOES_06_5001.geometry} material={materials['Modular_Characters.007']} skeleton={nodes.SHOES_06_5001.skeleton} />
            <skinnedMesh name="TORSO_19_2001" geometry={nodes.TORSO_19_2001.geometry} material={materials['Modular_Characters.007']} skeleton={nodes.TORSO_19_2001.skeleton} />
          </group>
        </group>
        <group name="Character_Male_Preset_02002" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="EmptyBeard004" />
          <group name="EmptyGlasses007" />
          <group name="EmptyHair004" />
          <group name="EmptyHat004" />
        </group>
        <group name="Armature001" position={[-2.835, 3.092, -4.855]} rotation={[1.597, 0.029, 0.11]} scale={0.008}>
          <primitive object={nodes.mixamorigHips_1} />
          <group name="GLASSES_03_2">
            <skinnedMesh name="Scene139" geometry={nodes.Scene139.geometry} material={materials['Modular_Characters.008']} skeleton={nodes.Scene139.skeleton} />
            <skinnedMesh name="Scene139_1" geometry={nodes.Scene139_1.geometry} material={materials['Modular_Characters_Transparent.002']} skeleton={nodes.Scene139_1.skeleton} />
          </group>
          <skinnedMesh name="HANDS_01_1001" geometry={nodes.HANDS_01_1001.geometry} material={materials['Modular_Characters.008']} skeleton={nodes.HANDS_01_1001.skeleton} />
          <skinnedMesh name="HAT_08_3" geometry={nodes.HAT_08_3.geometry} material={materials['Modular_Characters.008']} skeleton={nodes.HAT_08_3.skeleton} />
          <skinnedMesh name="HEAD_01_3" geometry={nodes.HEAD_01_3.geometry} material={materials['Modular_Characters.008']} skeleton={nodes.HEAD_01_3.skeleton} />
          <skinnedMesh name="PANTS_06_1" geometry={nodes.PANTS_06_1.geometry} material={materials['Modular_Characters.008']} skeleton={nodes.PANTS_06_1.skeleton} />
          <skinnedMesh name="SHOES_02_1" geometry={nodes.SHOES_02_1.geometry} material={materials['Modular_Characters.008']} skeleton={nodes.SHOES_02_1.skeleton} />
          <skinnedMesh name="TORSO_20_1" geometry={nodes.TORSO_20_1.geometry} material={materials['Modular_Characters.008']} skeleton={nodes.TORSO_20_1.skeleton} />
        </group>
        <group name="WALKING" position={[0.724, 4.212, -5.373]} scale={0.802} />
        <group name="NurbsPath" position={[0.724, 4.212, -3.488]} rotation={[0, Math.PI / 2, 0]} />
        <group name="Character_Female_Preset_06001" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="EmptyGlasses008" />
          <group name="EmptyHead003" />
        </group>
        <group name="Woman" position={[-3.441, 3.055, 2.547]} rotation={[Math.PI, -1.125, Math.PI]} scale={0.738}>
          <group name="Armature005" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <primitive object={nodes.mixamorigHips_2} />
            <skinnedMesh name="HAIR_07_2001" geometry={nodes.HAIR_07_2001.geometry} material={materials['Modular_Characters.001']} skeleton={nodes.HAIR_07_2001.skeleton} />
            <skinnedMesh name="HANDS_01_1002" geometry={nodes.HANDS_01_1002.geometry} material={materials['Modular_Characters.001']} skeleton={nodes.HANDS_01_1002.skeleton} />
            <skinnedMesh name="HEAD_01_2002" geometry={nodes.HEAD_01_2002.geometry} material={materials['Modular_Characters.001']} skeleton={nodes.HEAD_01_2002.skeleton} />
            <skinnedMesh name="PANTS_07_4001" geometry={nodes.PANTS_07_4001.geometry} material={materials['Modular_Characters.001']} skeleton={nodes.PANTS_07_4001.skeleton} />
            <skinnedMesh name="SHOES_06_1002" geometry={nodes.SHOES_06_1002.geometry} material={materials['Modular_Characters.001']} skeleton={nodes.SHOES_06_1002.skeleton} />
            <skinnedMesh name="TORSO_09_3001" geometry={nodes.TORSO_09_3001.geometry} material={materials['Modular_Characters.001']} skeleton={nodes.TORSO_09_3001.skeleton} />
          </group>
        </group>
        <group name="Character_Male_Preset_05001" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="EmptyBeard005" />
          <group name="EmptyGlasses009" />
          <group name="EmptyHair005" />
          <group name="EmptyHat005" />
        </group>
        <group name="Bosse" position={[-2.16, 3.231, -6.369]} rotation={[-0.001, 0.747, -0.015]} scale={0.718}>
          <group name="Armature007" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <primitive object={nodes.mixamorigHips_3} />
            <skinnedMesh name="BEARD_04_2001" geometry={nodes.BEARD_04_2001.geometry} material={materials['Modular_Characters.006']} skeleton={nodes.BEARD_04_2001.skeleton} />
            <skinnedMesh name="GLASSES_02_1001" geometry={nodes.GLASSES_02_1001.geometry} material={materials['Modular_Characters.006']} skeleton={nodes.GLASSES_02_1001.skeleton} />
            <skinnedMesh name="HANDS_01_1005" geometry={nodes.HANDS_01_1005.geometry} material={materials['Modular_Characters.006']} skeleton={nodes.HANDS_01_1005.skeleton} />
            <skinnedMesh name="HEAD_01_2003" geometry={nodes.HEAD_01_2003.geometry} material={materials['Modular_Characters.006']} skeleton={nodes.HEAD_01_2003.skeleton} />
            <skinnedMesh name="PANTS_05_3001" geometry={nodes.PANTS_05_3001.geometry} material={materials['Modular_Characters.006']} skeleton={nodes.PANTS_05_3001.skeleton} />
            <skinnedMesh name="SHOES_02_3001" geometry={nodes.SHOES_02_3001.geometry} material={materials['Modular_Characters.006']} skeleton={nodes.SHOES_02_3001.skeleton} />
            <skinnedMesh name="TORSO_06_2001" geometry={nodes.TORSO_06_2001.geometry} material={materials['Modular_Characters.006']} skeleton={nodes.TORSO_06_2001.skeleton} />
          </group>
        </group>
        <group name="Character_Male_Preset_16" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="EmptyBeard006" />
          <group name="EmptyGlasses010" />
          <group name="EmptyHair006" />
          <group name="EmptyHat006" />
        </group>
        <group name="Arstist03" position={[-3.345, 3.095, 1.783]} rotation={[0, -0.564, 0]} scale={0.76}>
          <group name="Armature008" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <primitive object={nodes.mixamorigHips_4} />
            <skinnedMesh name="HAIR_03_3" geometry={nodes.HAIR_03_3.geometry} material={materials['Modular_Characters.009']} skeleton={nodes.HAIR_03_3.skeleton} />
            <skinnedMesh name="HANDS_01_1007" geometry={nodes.HANDS_01_1007.geometry} material={materials['Modular_Characters.009']} skeleton={nodes.HANDS_01_1007.skeleton} />
            <skinnedMesh name="HEAD_01_3001" geometry={nodes.HEAD_01_3001.geometry} material={materials['Modular_Characters.009']} skeleton={nodes.HEAD_01_3001.skeleton} />
            <skinnedMesh name="PANTS_13_4" geometry={nodes.PANTS_13_4.geometry} material={materials['Modular_Characters.009']} skeleton={nodes.PANTS_13_4.skeleton} />
            <skinnedMesh name="SHOES_05_4" geometry={nodes.SHOES_05_4.geometry} material={materials['Modular_Characters.009']} skeleton={nodes.SHOES_05_4.skeleton} />
            <skinnedMesh name="TORSO_12_4" geometry={nodes.TORSO_12_4.geometry} material={materials['Modular_Characters.009']} skeleton={nodes.TORSO_12_4.skeleton} />
          </group>
        </group>
        <group name="Area006" position={[5.968, 3.463, -0.006]} rotation={[1.571, 1.565, -3.142]} scale={[5.195, 8.984, 1.939]} />
        <group name="Area007" position={[-11.665, 0.08, -0.006]} rotation={[-1.977, -1.2, 2.667]} scale={[5.195, 8.984, 1.939]} />
        <group name="Area008" position={[-1.591, -0.975, 16.418]} rotation={[-0.341, -0.092, -1.645]} scale={[5.195, 8.984, 1.939]} />
        <group name="Area009" position={[-1.487, 4.067, -13.35]} rotation={[-2.801, -0.067, 1.553]} scale={[5.195, 8.984, 1.939]} />
        <group name="EmptyHair" position={[7.379, 0.785, -0.04]} rotation={[Math.PI / 2, 0, 0]} scale={[0.011, 0.009, 0.008]} />
        <group name="EmptyHat" position={[7.379, 0.785, -0.04]} rotation={[Math.PI / 2, 0, 0]} scale={[0.011, 0.009, 0.008]} />
        <group name="EmptyGlasses" position={[7.379, 0.785, -0.04]} rotation={[Math.PI / 2, 0, 0]} scale={[0.011, 0.009, 0.008]} />
        <group name="EmptyBeard" position={[7.379, 0.785, -0.04]} rotation={[Math.PI / 2, 0, 0]} scale={[0.011, 0.009, 0.008]} />
        <group name="Character_Male_Preset_02" position={[7.379, 0.785, -0.04]} rotation={[Math.PI / 2, 0, 0]} scale={[0.011, 0.009, 0.008]} />
        <group name="EmptyHair001" position={[7.379, 0.785, -0.04]} rotation={[Math.PI / 2, 0, 0]} scale={[0.011, 0.009, 0.008]} />
        <group name="EmptyHat001" position={[7.379, 0.785, -0.04]} rotation={[Math.PI / 2, 0, 0]} scale={[0.011, 0.009, 0.008]} />
        <group name="EmptyGlasses001" position={[7.379, 0.785, -0.04]} rotation={[Math.PI / 2, 0, 0]} scale={[0.011, 0.009, 0.008]} />
        <group name="EmptyBeard001" position={[7.379, 0.785, -0.04]} rotation={[Math.PI / 2, 0, 0]} scale={[0.011, 0.009, 0.008]} />
        <group name="Character_Male_Preset_02001" position={[7.379, 0.785, -0.04]} rotation={[Math.PI / 2, 0, 0]} scale={[0.011, 0.009, 0.008]} />
        <group name="EmptyHair002" position={[7.379, 0.785, -0.04]} rotation={[Math.PI / 2, 0, 0]} scale={[0.011, 0.009, 0.008]} />
        <group name="EmptyHat002" position={[7.379, 0.785, -0.04]} rotation={[Math.PI / 2, 0, 0]} scale={[0.011, 0.009, 0.008]} />
        <group name="EmptyGlasses002" position={[7.379, 0.785, -0.04]} rotation={[Math.PI / 2, 0, 0]} scale={[0.011, 0.009, 0.008]} />
        <group name="EmptyBeard002" position={[7.379, 0.785, -0.04]} rotation={[Math.PI / 2, 0, 0]} scale={[0.011, 0.009, 0.008]} />
        <group name="Character_Male_Preset_05" position={[7.379, 0.785, -0.04]} rotation={[Math.PI / 2, 0, 0]} scale={[0.011, 0.009, 0.008]} />
        <group name="EmptyHair003" position={[7.379, 0.785, -0.04]} rotation={[Math.PI / 2, 0, 0]} scale={[0.011, 0.009, 0.008]} />
        <group name="EmptyHat003" position={[7.379, 0.785, -0.04]} rotation={[Math.PI / 2, 0, 0]} scale={[0.011, 0.009, 0.008]} />
        <group name="EmptyGlasses003" position={[7.379, 0.785, -0.04]} rotation={[Math.PI / 2, 0, 0]} scale={[0.011, 0.009, 0.008]} />
        <group name="EmptyBeard003" position={[7.379, 0.785, -0.04]} rotation={[Math.PI / 2, 0, 0]} scale={[0.011, 0.009, 0.008]} />
        <group name="Character_Male_Preset_07" position={[7.379, 0.785, -0.04]} rotation={[Math.PI / 2, 0, 0]} scale={[0.011, 0.009, 0.008]} />
        <group name="DEV01" position={[2.718, 4.337, -6.052]} rotation={[-Math.PI, 0.027, -Math.PI]} scale={0.73}>
          <group name="Armature003" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <primitive object={nodes.mixamorigHips_5} />
            <skinnedMesh name="HAIR_07_1" geometry={nodes.HAIR_07_1.geometry} material={materials['Modular_Characters.004']} skeleton={nodes.HAIR_07_1.skeleton} />
            <skinnedMesh name="HANDS_01_1003" geometry={nodes.HANDS_01_1003.geometry} material={materials['Modular_Characters.004']} skeleton={nodes.HANDS_01_1003.skeleton} />
            <skinnedMesh name="HEAD_01_1001" geometry={nodes.HEAD_01_1001.geometry} material={materials['Modular_Characters.004']} skeleton={nodes.HEAD_01_1001.skeleton} />
            <skinnedMesh name="PANTS_13_5" geometry={nodes.PANTS_13_5.geometry} material={materials['Modular_Characters.004']} skeleton={nodes.PANTS_13_5.skeleton} />
            <skinnedMesh name="SHOES_02_5" geometry={nodes.SHOES_02_5.geometry} material={materials['Modular_Characters.004']} skeleton={nodes.SHOES_02_5.skeleton} />
            <skinnedMesh name="TORSO_16_5" geometry={nodes.TORSO_16_5.geometry} material={materials['Modular_Characters.004']} skeleton={nodes.TORSO_16_5.skeleton} />
          </group>
        </group>
        <group name="EmptyHead" position={[7.379, 0.785, -0.04]} rotation={[Math.PI / 2, 0, 0]} scale={[0.011, 0.009, 0.008]} />
        <group name="EmptyGlasses004" position={[7.379, 0.785, -0.04]} rotation={[Math.PI / 2, 0, 0]} scale={[0.011, 0.009, 0.008]} />
        <group name="Character_Female_Preset_06" position={[7.379, 0.785, -0.04]} rotation={[Math.PI / 2, 0, 0]} scale={[0.011, 0.009, 0.008]} />
        <group name="EmptyHead001" position={[7.379, 0.785, -0.04]} rotation={[Math.PI / 2, 0, 0]} scale={[0.011, 0.009, 0.008]} />
        <group name="EmptyGlasses005" position={[7.379, 0.785, -0.04]} rotation={[Math.PI / 2, 0, 0]} scale={[0.011, 0.009, 0.008]} />
        <group name="Character_Female_Preset_11" position={[7.379, 0.785, -0.04]} rotation={[Math.PI / 2, 0, 0]} scale={[0.011, 0.009, 0.008]} />
        <spotLight intensity={54.351} angle={Math.PI / 8} penumbra={0.15} decay={2} color="#fff2f5" position={[1.159, 8.069, -4.731]} rotation={[-Math.PI / 2, 0.006, 0]} scale={[5.195, 8.984, 1.939]} target={nodes.Area.target}>
          <primitive object={nodes.Area.target} position={[0, 0, -1]} />
        </spotLight>
        <PerspectiveCamera name="Camera01" makeDefault={true} far={1000} near={0.1} fov={39.598} position={[-23.128, 23.72, 24.714]} rotation={[-0.705, -0.629, -0.465]} />
        <spotLight intensity={54.351} angle={Math.PI / 8} penumbra={0.15} decay={2} color="#fff2f5" position={[1.159, 8.069, -0.387]} rotation={[-Math.PI / 2, 0.006, 0]} scale={[5.195, 8.984, 1.939]} target={nodes.Area010.target}>
          <primitive object={nodes.Area010.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={54.351} angle={Math.PI / 8} penumbra={0.15} decay={2} color="#fff2f5" position={[1.159, 8.069, 3.731]} rotation={[-Math.PI / 2, 0.006, 0]} scale={[5.195, 8.984, 1.939]} target={nodes.Area011.target}>
          <primitive object={nodes.Area011.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={54.351} angle={Math.PI / 8} penumbra={0.15} decay={2} color="#fff2f5" position={[1.159, 8.069, 7.493]} rotation={[-Math.PI / 2, 0.006, 0]} scale={[5.195, 8.984, 1.939]} target={nodes.Area012.target}>
          <primitive object={nodes.Area012.target} position={[0, 0, -1]} />
        </spotLight>
        <mesh name="office_chair_022" geometry={nodes.office_chair_022.geometry} material={materials['Color.027']} position={[0.199, 3.075, 6.46]} rotation={[Math.PI / 2, 0, 0.992]} scale={[0.013, 0.013, 0.01]} />
        <mesh name="office_chair_022_1" geometry={nodes.office_chair_022_1.geometry} material={materials['Color.027']} position={[-1.857, 3.075, 1.954]} rotation={[Math.PI / 2, 0, 1.756]} scale={[0.011, 0.011, 0.009]} />
        <mesh name="Walls_011001" geometry={nodes.Walls_011001.geometry} material={materials['Color.002']} position={[2.398, 4.113, 1.668]} rotation={[Math.PI, 0, 0]} scale={[0.011, 0.009, 0.01]} />
        <group name="Walls_011002" position={[-2.14, 2.987, -2.263]} rotation={[Math.PI, 0, 0]} scale={[0.011, 0.009, 0.01]}>
          <mesh name="Scene178" geometry={nodes.Scene178.geometry} material={materials['Color.021']} />
          <mesh name="Scene178_1" geometry={nodes.Scene178_1.geometry} material={materials['Material.147']} />
        </group>
        <group name="Walls_011003" position={[-2.14, 2.987, 1.668]} rotation={[Math.PI, 0, 0]} scale={[0.011, 0.009, 0.01]}>
          <mesh name="Scene180" geometry={nodes.Scene180.geometry} material={materials['Color.021']} />
          <mesh name="Scene180_1" geometry={nodes.Scene180_1.geometry} material={materials['Material.147']} />
        </group>
        <mesh name="Walls_011004" geometry={nodes.Walls_011004.geometry} material={materials['Color.002']} position={[2.398, 4.113, 5.603]} rotation={[Math.PI, 0, 0]} scale={[0.011, 0.009, 0.01]} />
        <group name="Walls_011005" position={[-2.14, 2.987, 5.603]} rotation={[Math.PI, 0, 0]} scale={[0.011, 0.009, 0.01]}>
          <mesh name="Scene201" geometry={nodes.Scene201.geometry} material={materials['Color.021']} />
          <mesh name="Scene201_1" geometry={nodes.Scene201_1.geometry} material={materials['Material.147']} />
        </group>
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Material.138']} position={[0.089, 1.909, 2.4]} scale={[4.807, 0.975, 10.966]} />
        <mesh name="Walls_011008" geometry={nodes.Walls_011008.geometry} material={materials['Color.002']} position={[2.398, 4.113, -2.257]} rotation={[Math.PI, 0, 0]} scale={[0.011, 0.009, 0.01]} />
        <mesh name="Stairs_098001" geometry={nodes.Stairs_098001.geometry} material={materials['Color.002']} position={[-0.08, 3.51, 6.175]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.019, 0.021, 0.019]} />
        <mesh name="Walls_011009" geometry={nodes.Walls_011009.geometry} material={materials['Color.021']} position={[-2.14, 2.987, -7.088]} rotation={[Math.PI, 0, 0]} scale={[0.011, 0.009, 0.01]} />
        <group name="Walls_011010" position={[2.398, 4.113, -7.082]} rotation={[Math.PI, 0, 0]} scale={[0.011, 0.009, 0.01]}>
          <mesh name="Scene270" geometry={nodes.Scene270.geometry} material={materials['Color.002']} />
          <mesh name="Scene270_1" geometry={nodes.Scene270_1.geometry} material={materials['Material.146']} />
        </group>
        <mesh name="shelf_048" geometry={nodes.shelf_048.geometry} material={materials['Color.024']} position={[4.135, 4.192, -2.068]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.013, 0.015, 0.011]} />
        <mesh name="shelf_048001" geometry={nodes.shelf_048001.geometry} material={materials['Color.024']} position={[4.135, 4.192, 3.1]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.013, 0.015, 0.011]} />
        <mesh name="office_chair_022_1001" geometry={nodes.office_chair_022_1001.geometry} material={materials['Color.027']} position={[-1.857, 3.075, 0.426]} rotation={[Math.PI / 2, 0, 0.571]} scale={[0.011, 0.011, 0.009]} />
        <mesh name="office_chair_022_1002" geometry={nodes.office_chair_022_1002.geometry} material={materials['Color.027']} position={[-1.922, 3.075, -2.796]} rotation={[Math.PI / 2, 0, 1.804]} scale={[0.011, 0.011, 0.009]} />
        <mesh name="office_chair_022_1003" geometry={nodes.office_chair_022_1003.geometry} material={materials['Color.027']} position={[-2.081, 3.075, -4.412]} rotation={[Math.PI / 2, 0, 0.511]} scale={[0.011, 0.011, 0.009]} />
        <mesh name="office_table_017" geometry={nodes.office_table_017.geometry} material={materials['Color.025']} position={[-4.052, 3.079, 2.41]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.01, 0.011, 0.008]} />
        <mesh name="sofa_006" geometry={nodes.sofa_006.geometry} material={materials['Color.027']} position={[-3.817, 3.069, 0.35]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.01, 0.011, 0.008]} />
        <mesh name="office_table_017001" geometry={nodes.office_table_017001.geometry} material={materials['Color.025']} position={[-4.04, 3.088, -1.787]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.01, 0.011, 0.008]} />
        <mesh name="sofa_006001" geometry={nodes.sofa_006001.geometry} material={materials['Color.027']} position={[-3.806, 3.085, -3.927]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.01, 0.011, 0.008]} />
        <mesh name="office_table_017002" geometry={nodes.office_table_017002.geometry} material={materials['Color.025']} position={[-4.04, 3.088, -6.056]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.01, 0.011, 0.008]} />
        <mesh name="Partitions_017" geometry={nodes.Partitions_017.geometry} material={materials['Material.147']} position={[0.813, 4.174, 3.378]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Partitions_017001" geometry={nodes.Partitions_017001.geometry} material={materials['Material.147']} position={[-1.143, 4.174, 3.378]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
        <mesh name="Partitions_017002" geometry={nodes.Partitions_017002.geometry} material={materials['Material.147']} position={[-1.143, 4.174, 1.366]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
        <mesh name="Partitions_017003" geometry={nodes.Partitions_017003.geometry} material={materials['Material.147']} position={[-1.143, 4.174, -0.645]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
        <mesh name="Partitions_017004" geometry={nodes.Partitions_017004.geometry} material={materials['Material.147']} position={[-1.143, 4.174, -2.657]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
        <mesh name="Partitions_017005" geometry={nodes.Partitions_017005.geometry} material={materials['Material.147']} position={[-1.143, 4.174, -4.665]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
        <mesh name="Partitions_017006" geometry={nodes.Partitions_017006.geometry} material={materials['Material.147']} position={[-1.143, 4.174, -6.676]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
        <mesh name="office_table_017003" geometry={nodes.office_table_017003.geometry} material={materials['Material.147']} position={[-0.597, 4.197, -0.449]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.01, 0.011, 0.008]} />
        <mesh name="office_table_017004" geometry={nodes.office_table_017004.geometry} material={materials['Material.147']} position={[-0.597, 4.197, -2.437]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.01, 0.011, 0.008]} />
        <mesh name="office_chair_022_1004" geometry={nodes.office_chair_022_1004.geometry} material={materials['Color.027']} position={[-0.268, 4.142, 0.901]} rotation={[Math.PI / 2, 0, -0.554]} scale={[0.011, 0.011, 0.009]} />
        <mesh name="office_table_017005" geometry={nodes.office_table_017005.geometry} material={materials['Material.147']} position={[0.721, 4.197, -6.558]} rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.011, 0.008]} />
        <mesh name="office_table_017006" geometry={nodes.office_table_017006.geometry} material={materials['Material.147']} position={[2.709, 4.197, -6.558]} rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.011, 0.008]} />
        <mesh name="office_chair_017" geometry={nodes.office_chair_017.geometry} material={materials['Color.029']} position={[-3.476, 3.099, 2.565]} rotation={[Math.PI / 2, 0, 2.258]} scale={0.008} />
        <mesh name="office_chair_017001" geometry={nodes.office_chair_017001.geometry} material={materials['Color.029']} position={[-3.604, 3.099, -1.825]} rotation={[Math.PI / 2, 0, 1.388]} scale={0.008} />
        <mesh name="office_chair_017002" geometry={nodes.office_chair_017002.geometry} material={materials['Color.029']} position={[-3.604, 3.099, -6.134]} rotation={[Math.PI / 2, 0, 1.623]} scale={0.008} />
        <mesh name="office_chair_017003" geometry={nodes.office_chair_017003.geometry} material={materials['Color.029']} position={[-0.169, 4.202, -2.516]} rotation={[Math.PI / 2, 0, 1.623]} scale={0.008} />
        <mesh name="office_chair_017004" geometry={nodes.office_chair_017004.geometry} material={materials['Color.029']} position={[-0.169, 4.202, -0.435]} rotation={[Math.PI / 2, 0, 1.945]} scale={0.008} />
        <mesh name="office_chair_017005" geometry={nodes.office_chair_017005.geometry} material={materials['Color.029']} position={[0.621, 4.194, -6.129]} rotation={[Math.PI / 2, 0, -2.496]} scale={0.008} />
        <mesh name="office_chair_017006" geometry={nodes.office_chair_017006.geometry} material={materials['Color.029']} position={[2.725, 4.203, -6.084]} rotation={[Math.PI / 2, 0, -3.112]} scale={0.008} />
        <mesh name="office_chair_022_1005" geometry={nodes.office_chair_022_1005.geometry} material={materials['Color.024']} position={[3.526, 4.142, 2.17]} rotation={[Math.PI / 2, 0, 1.764]} scale={[0.011, 0.011, 0.009]} />
        <mesh name="office_table_031" geometry={nodes.office_table_031.geometry} material={materials.Color} position={[-1.749, 3.089, -6.127]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.008} />
        <mesh name="office_chair_001001" geometry={nodes.office_chair_001001.geometry} material={materials['Color.011']} position={[-2.222, 3.087, -6.389]} rotation={[Math.PI / 2, 0, -0.816]} scale={0.008} />
        <mesh name="electronics_032" geometry={nodes.electronics_032.geometry} material={materials['Color.026']} position={[-1.681, 3.066, -6.896]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.009} />
        <mesh name="electronics_024" geometry={nodes.electronics_024.geometry} material={materials['Color.028']} position={[-1.572, 3.732, -6.15]} rotation={[Math.PI / 2, 0, 2.117]} scale={0.008} />
        <mesh name="electronics_024001" geometry={nodes.electronics_024001.geometry} material={materials['Color.028']} position={[-1.967, 3.732, -5.745]} rotation={[Math.PI / 2, 0, 2.559]} scale={0.008} />
        <mesh name="electronics_029" geometry={nodes.electronics_029.geometry} material={materials['Color.030']} position={[-1.893, 3.773, -6.084]} rotation={[Math.PI / 2, 0, 2.356]} scale={0.01} />
        <mesh name="flower_024" geometry={nodes.flower_024.geometry} material={materials['Color.032']} position={[-1.574, 3.752, -6.875]} rotation={[Math.PI / 2, 0, 0]} scale={0.005} />
        <mesh name="electronics_024002" geometry={nodes.electronics_024002.geometry} material={materials['Color.028']} position={[-4.083, 3.732, -6.108]} rotation={[Math.PI / 2, 0, -1.618]} scale={0.008} />
        <mesh name="electronics_011" geometry={nodes.electronics_011.geometry} material={materials['Color.035']} position={[-3.928, 3.726, -1.77]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.009} />
        <mesh name="electronics_029001" geometry={nodes.electronics_029001.geometry} material={materials['Color.030']} position={[-3.898, 3.738, -2.056]} rotation={[Math.PI / 2, 0, -1.724]} scale={0.01} />
        <mesh name="electronics_011001" geometry={nodes.electronics_011001.geometry} material={materials['Color.035']} position={[-3.928, 3.714, 2.38]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.009} />
        <mesh name="electronics_029002" geometry={nodes.electronics_029002.geometry} material={materials['Color.030']} position={[-3.898, 3.726, 2.093]} rotation={[Math.PI / 2, 0, -1.724]} scale={0.01} />
        <mesh name="prop_101" geometry={nodes.prop_101.geometry} material={materials['Color.038']} position={[-4.011, 3.726, -2.176]} rotation={[Math.PI / 2, 0, 0]} scale={0.006} />
        <mesh name="electronics_024003" geometry={nodes.electronics_024003.geometry} material={materials['Color.028']} position={[0.627, 4.866, -6.624]} rotation={[Math.PI / 2, 0, 0.077]} scale={0.008} />
        <mesh name="electronics_029003" geometry={nodes.electronics_029003.geometry} material={materials['Color.030']} position={[0.607, 4.857, -6.437]} rotation={[Math.PI / 2, 0, 0.072]} scale={0.01} />
        <mesh name="electronics_011002" geometry={nodes.electronics_011002.geometry} material={materials['Color.035']} position={[2.66, 4.833, -6.568]} rotation={[Math.PI / 2, 0, 0.011]} scale={0.009} />
        <mesh name="electronics_029004" geometry={nodes.electronics_029004.geometry} material={materials['Color.030']} position={[2.969, 4.846, -6.363]} rotation={[Math.PI / 2, 0, -0.143]} scale={0.01} />
        <mesh name="prop_037001" geometry={nodes.prop_037001.geometry} material={materials['Color.039']} position={[-3.999, 3.725, -5.649]} rotation={[Math.PI / 2, 0, 0]} scale={0.006} />
        <mesh name="electronics_011003" geometry={nodes.electronics_011003.geometry} material={materials['Color.035']} position={[-0.693, 4.832, -0.402]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.009} />
        <mesh name="electronics_029005" geometry={nodes.electronics_029005.geometry} material={materials['Color.030']} position={[-0.663, 4.844, -0.688]} rotation={[Math.PI / 2, 0, -1.724]} scale={0.01} />
        <mesh name="prop_101001" geometry={nodes.prop_101001.geometry} material={materials['Color.038']} position={[-0.776, 4.832, -0.809]} rotation={[Math.PI / 2, 0, 0]} scale={0.006} />
        <mesh name="electronics_024005" geometry={nodes.electronics_024005.geometry} material={materials['Color.028']} position={[-0.691, 4.862, -2.316]} rotation={[Math.PI / 2, 0, -1.551]} scale={0.008} />
        <mesh name="electronics_029006" geometry={nodes.electronics_029006.geometry} material={materials['Color.030']} position={[-0.503, 4.861, -2.279]} rotation={[Math.PI / 2, 0, -1.556]} scale={0.01} />
        <mesh name="electronics_011004" geometry={nodes.electronics_011004.geometry} material={materials['Color.035']} position={[-0.563, 4.833, -2.885]} rotation={[Math.PI / 2, 0, -0.758]} scale={0.009} />
        <mesh name="prop_037002" geometry={nodes.prop_037002.geometry} material={materials['Color.039']} position={[3.137, 4.833, -6.583]} rotation={[Math.PI / 2, 0, 0]} scale={0.006} />
        <mesh name="lamp_013" geometry={nodes.lamp_013.geometry} material={materials['Color.040']} position={[0.279, 4.836, -6.63]} rotation={[Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh name="musical_instrument_006" geometry={nodes.musical_instrument_006.geometry} material={materials['Color.041']} position={[2.364, 4.834, -6.609]} rotation={[Math.PI / 2, 0, 0]} scale={0.003} />
        <mesh name="musical_instrument_006001" geometry={nodes.musical_instrument_006001.geometry} material={materials['Color.041']} position={[2.951, 4.834, -6.609]} rotation={[Math.PI / 2, 0, 0]} scale={0.003} />
        <mesh name="flower_001" geometry={nodes.flower_001.geometry} material={materials['Color.042']} position={[3.869, 4.216, -3.201]} rotation={[Math.PI / 2, 0, 0]} scale={0.013} />
        <mesh name="picture_033" geometry={nodes.picture_033.geometry} material={materials['Color.043']} position={[-2.428, 4.675, -7.138]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="picture_033001" geometry={nodes.picture_033001.geometry} material={materials['Color.043']} position={[-3.438, 4.682, -7.14]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="coffee_table_014" geometry={nodes.coffee_table_014.geometry} material={materials['Color.044']} position={[0.263, 4.216, 1.806]} rotation={[Math.PI / 2, 0, 0]} scale={0.009} />
        <mesh name="prop_101002" geometry={nodes.prop_101002.geometry} material={materials['Color.038']} position={[0.396, 4.486, 1.71]} rotation={[Math.PI / 2, 0, 2.359]} scale={0.006} />
        <mesh name="prop_101003" geometry={nodes.prop_101003.geometry} material={materials['Color.038']} position={[0.324, 4.486, 1.638]} rotation={[Math.PI / 2, 0, 2.359]} scale={0.006} />
        <mesh name="prop_077" geometry={nodes.prop_077.geometry} material={materials['Color.045']} position={[4.089, 6.064, -2.397]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
        <mesh name="shop_065" geometry={nodes.shop_065.geometry} material={materials['Color.046']} position={[0.244, 4.479, 1.83]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="prop_081001" geometry={nodes.prop_081001.geometry} material={materials['Color.047']} position={[4.15, 4.735, 2.762]} rotation={[Math.PI / 2, 0, 1.679]} scale={0.013} />
        <mesh name="prop_076" geometry={nodes.prop_076.geometry} material={materials['Color.048']} position={[4.222, 5.726, -1.818]} rotation={[Math.PI / 2, 0, 0]} scale={0.014} />
        <mesh name="prop_076001" geometry={nodes.prop_076001.geometry} material={materials['Color.048']} position={[4.068, 5.726, -1.533]} rotation={[Math.PI / 2, 0, 0]} scale={0.014} />
        <mesh name="prop_076002" geometry={nodes.prop_076002.geometry} material={materials['Color.048']} position={[4.215, 5.726, -1.163]} rotation={[Math.PI / 2, 0, 0]} scale={0.014} />
        <mesh name="prop_086" geometry={nodes.prop_086.geometry} material={materials['Color.049']} position={[4.092, 5.707, -2.222]} rotation={[Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh name="prop_080" geometry={nodes.prop_080.geometry} material={materials['Color.050']} position={[4.225, 5.059, 2.655]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.012} />
        <mesh name="prop_076003" geometry={nodes.prop_076003.geometry} material={materials['Color.048']} position={[4.178, 5.059, 3.083]} rotation={[Math.PI / 2, 0, 0]} scale={0.014} />
        <mesh name="prop_076004" geometry={nodes.prop_076004.geometry} material={materials['Color.048']} position={[4.139, 5.059, 3.238]} rotation={[Math.PI / 2, 0, 0]} scale={0.014} />
        <mesh name="prop_076005" geometry={nodes.prop_076005.geometry} material={materials['Color.048']} position={[4.186, 5.059, 3.424]} rotation={[Math.PI / 2, 0, 0]} scale={0.014} />
        <mesh name="prop_076006" geometry={nodes.prop_076006.geometry} material={materials['Color.048']} position={[4.186, 5.059, 3.88]} rotation={[Math.PI / 2, 0, 0]} scale={0.014} />
        <mesh name="prop_076007" geometry={nodes.prop_076007.geometry} material={materials['Color.048']} position={[4.186, 5.059, 4.176]} rotation={[Math.PI / 2, 0, 0]} scale={0.014} />
        <mesh name="prop_086001" geometry={nodes.prop_086001.geometry} material={materials['Color.049']} position={[4.136, 4.318, 3.07]} rotation={[Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh name="prop_078" geometry={nodes.prop_078.geometry} material={materials['Color.051']} position={[4.142, 4.714, 4.796]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.014} />
        <mesh name="prop_078001" geometry={nodes.prop_078001.geometry} material={materials['Color.051']} position={[4.142, 5.046, -0.358]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.014} />
        <mesh name="flower_020002" geometry={nodes.flower_020002.geometry} material={materials['Color.052']} position={[4.153, 5.389, -2.397]} rotation={[Math.PI / 2, 0, 0]} scale={0.009} />
        <mesh name="flower_020003" geometry={nodes.flower_020003.geometry} material={materials['Color.052']} position={[4.153, 5.389, 3.614]} rotation={[Math.PI / 2, 0, 0]} scale={0.009} />
        <mesh name="flower_020004" geometry={nodes.flower_020004.geometry} material={materials['Color.052']} position={[4.153, 5.73, 4.327]} rotation={[Math.PI / 2, 0, 0]} scale={0.009} />
        <mesh name="flower_020005" geometry={nodes.flower_020005.geometry} material={materials['Color.052']} position={[4.153, 5.394, 4.813]} rotation={[Math.PI / 2, 0, 0]} scale={0.009} />
        <mesh name="prop_035" geometry={nodes.prop_035.geometry} material={materials['Color.053']} position={[4.148, 4.351, -0.738]} rotation={[Math.PI / 2, 0, 0.283]} scale={0.008} />
        <mesh name="prop_035001" geometry={nodes.prop_035001.geometry} material={materials['Color.053']} position={[4.148, 4.351, -0.378]} rotation={[Math.PI / 2, 0, 0.283]} scale={0.008} />
        <mesh name="prop_035002" geometry={nodes.prop_035002.geometry} material={materials['Color.053']} position={[4.148, 4.351, 4.501]} rotation={[Math.PI / 2, 0, 0.283]} scale={0.008} />
        <mesh name="prop_035003" geometry={nodes.prop_035003.geometry} material={materials['Color.053']} position={[4.148, 4.351, 4.819]} rotation={[Math.PI / 2, 0, -0.019]} scale={0.008} />
        <mesh name="prop_035004" geometry={nodes.prop_035004.geometry} material={materials['Color.053']} position={[4.148, 4.721, 3.822]} rotation={[Math.PI / 2, 0, 0.283]} scale={0.008} />
        <mesh name="prop_035005" geometry={nodes.prop_035005.geometry} material={materials['Color.053']} position={[4.148, 4.721, 4.141]} rotation={[Math.PI / 2, 0, 0.026]} scale={0.008} />
        <mesh name="prop_035006" geometry={nodes.prop_035006.geometry} material={materials['Color.053']} position={[4.148, 4.721, 3.353]} rotation={[Math.PI / 2, 0, 0.026]} scale={0.008} />
        <mesh name="prop_081002" geometry={nodes.prop_081002.geometry} material={materials['Color.047']} position={[4.15, 4.735, -2.229]} rotation={[Math.PI / 2, 0, 1.679]} scale={0.013} />
        <mesh name="shop_038" geometry={nodes.shop_038.geometry} material={materials['Color.055']} position={[4.145, 5.051, -1.407]} rotation={[Math.PI / 2, 0, -2.985]} scale={0.007} />
        <mesh name="flower_013" geometry={nodes.flower_013.geometry} material={materials['Color.056']} position={[4.138, 6.056, 2.908]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="electronics_032001" geometry={nodes.electronics_032001.geometry} material={materials['Color.026']} position={[1.164, 4.195, -6.497]} rotation={[Math.PI / 2, 0, 0]} scale={0.007} />
        <mesh name="electronics_032002" geometry={nodes.electronics_032002.geometry} material={materials['Color.026']} position={[-0.535, 4.195, -1.95]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.007} />
        <mesh name="electronics_032003" geometry={nodes.electronics_032003.geometry} material={materials['Color.026']} position={[-3.959, 3.079, -5.558]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.007} />
        <mesh name="prop_013" geometry={nodes.prop_013.geometry} material={materials['Color.057']} position={[-2.013, 3.077, 2.706]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="training_item_002" geometry={nodes.training_item_002.geometry} material={materials['Color.058']} position={[-1.619, 3.077, 3.186]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="floor_006006" geometry={nodes.floor_006006.geometry} material={materials['Color.002']} position={[-3.013, 3.08, -1.062]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.007, 0.005]} />
        <mesh name="floor_006008" geometry={nodes.floor_006008.geometry} material={materials['Color.002']} position={[-0.218, 3.086, -1.062]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.007, 0.005]} />
        <mesh name="floor_006009" geometry={nodes.floor_006009.geometry} material={materials['Color.002']} position={[2.338, 4.205, -1.062]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.008, 0.005]} />
        <mesh name="floor_006010" geometry={nodes.floor_006010.geometry} material={materials['Color.002']} position={[5.33, 4.205, -1.062]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.008, 0.005]} />
        <mesh name="floor_006007" geometry={nodes.floor_006007.geometry} material={materials['Color.002']} position={[-3.013, 3.08, 1.367]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.007, 0.005]} />
        <mesh name="floor_006011" geometry={nodes.floor_006011.geometry} material={materials['Color.002']} position={[-0.218, 3.086, 1.367]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.007, 0.005]} />
        <mesh name="floor_006012" geometry={nodes.floor_006012.geometry} material={materials['Color.002']} position={[2.338, 4.205, 1.367]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.008, 0.005]} />
        <mesh name="floor_006013" geometry={nodes.floor_006013.geometry} material={materials['Color.002']} position={[5.33, 4.205, 1.367]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.008, 0.005]} />
        <mesh name="floor_006014" geometry={nodes.floor_006014.geometry} material={materials['Color.002']} position={[-3.013, 3.08, 3.785]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.007, 0.005]} />
        <mesh name="floor_006015" geometry={nodes.floor_006015.geometry} material={materials['Color.002']} position={[-0.218, 3.086, 3.785]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.007, 0.005]} />
        <mesh name="floor_006016" geometry={nodes.floor_006016.geometry} material={materials['Color.002']} position={[2.338, 4.205, 3.785]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.008, 0.005]} />
        <mesh name="floor_006017" geometry={nodes.floor_006017.geometry} material={materials['Color.002']} position={[5.33, 4.205, 3.785]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.008, 0.005]} />
        <mesh name="floor_006018" geometry={nodes.floor_006018.geometry} material={materials['Color.002']} position={[-3.013, 3.08, 6.285]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.007, 0.007, 0.005]} />
        <mesh name="floor_006019" geometry={nodes.floor_006019.geometry} material={materials['Color.002']} position={[-0.218, 3.086, 6.214]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.007, 0.005]} />
        <mesh name="floor_006020" geometry={nodes.floor_006020.geometry} material={materials['Color.002']} position={[2.338, 4.205, 6.214]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.008, 0.005]} />
        <mesh name="floor_006021" geometry={nodes.floor_006021.geometry} material={materials['Color.002']} position={[5.33, 4.205, 6.214]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.008, 0.005]} />
        <mesh name="floor_006030" geometry={nodes.floor_006030.geometry} material={materials['Color.002']} position={[-3.013, 3.08, -5.916]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.007, 0.005]} />
        <mesh name="floor_006031" geometry={nodes.floor_006031.geometry} material={materials['Color.002']} position={[-0.218, 3.086, -5.916]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.007, 0.005]} />
        <mesh name="floor_006032" geometry={nodes.floor_006032.geometry} material={materials['Color.002']} position={[2.338, 4.205, -5.916]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.008, 0.005]} />
        <mesh name="floor_006033" geometry={nodes.floor_006033.geometry} material={materials['Color.002']} position={[-3.013, 3.08, -3.488]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.007, 0.005]} />
        <mesh name="floor_006034" geometry={nodes.floor_006034.geometry} material={materials['Color.002']} position={[-0.218, 3.086, -3.488]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.007, 0.005]} />
        <mesh name="floor_006035" geometry={nodes.floor_006035.geometry} material={materials['Color.002']} position={[2.338, 4.205, -3.488]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.008, 0.005]} />
        <mesh name="Walls_006_2002" geometry={nodes.Walls_006_2002.geometry} material={materials['Material.020']} position={[4.454, 5.654, 4.043]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.016, 0.011, 0.009]} />
        <group name="Walls_006_1006" position={[4.485, 5.682, -4.66]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.011, 0.012, 0.002]}>
          <mesh name="Scene272" geometry={nodes.Scene272.geometry} material={materials['Color.020']} />
          <mesh name="Scene272_1" geometry={nodes.Scene272_1.geometry} material={materials['Material.148']} />
        </group>
        <mesh name="Walls_006_1009" geometry={nodes.Walls_006_1009.geometry} material={materials['Material.020']} position={[4.548, 5.682, -5.429]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.008, 0.011, 0.002]} />
        <group name="Walls_006_1010" position={[4.595, 5.549, 1.176]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.01, 0.014, 0.002]}>
          <mesh name="Scene276" geometry={nodes.Scene276.geometry} material={materials['Color.020']} />
          <mesh name="Scene276_1" geometry={nodes.Scene276_1.geometry} material={materials['Material.148']} />
        </group>
        <mesh name="floor_006036" geometry={nodes.floor_006036.geometry} material={materials['Color.002']} position={[5.33, 4.205, -5.898]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.008, 0.005]} />
        <mesh name="floor_006037" geometry={nodes.floor_006037.geometry} material={materials['Color.002']} position={[5.33, 4.205, -3.469]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.008, 0.005]} />
        <mesh name="Walls_006_1008" geometry={nodes.Walls_006_1008.geometry} material={materials['Material.020']} position={[4.453, 7.124, 2.719]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.008, 0.011, 0.002]} />
        <mesh name="floor_006022" geometry={nodes.floor_006022.geometry} material={materials['Color.002']} position={[-0.665, 4.205, 2.345]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.008, 0.005]} />
        <mesh name="floor_006023" geometry={nodes.floor_006023.geometry} material={materials['Color.002']} position={[-0.664, 4.205, -0.078]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.008, 0.005]} />
        <mesh name="floor_006024" geometry={nodes.floor_006024.geometry} material={materials['Color.002']} position={[-0.665, 4.205, -2.511]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.008, 0.005]} />
        <mesh name="floor_006025" geometry={nodes.floor_006025.geometry} material={materials['Color.002']} position={[-0.664, 4.205, -4.934]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.008, 0.005]} />
        <mesh name="floor_006026" geometry={nodes.floor_006026.geometry} material={materials['Color.002']} position={[-0.664, 4.205, -7.372]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.008, 0.005]} />
        <group name="Walls_006_1011" position={[2.223, 5.655, -7.228]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[0.009, 0.009, 0.002]}>
          <mesh name="Scene293" geometry={nodes.Scene293.geometry} material={materials['Material.020']} />
          <mesh name="Scene293_1" geometry={nodes.Scene293_1.geometry} material={materials.Material} />
        </group>
        <group name="Walls_006_1007" position={[4.595, 5.549, 6.233]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.01, 0.014, 0.002]}>
          <mesh name="Scene299" geometry={nodes.Scene299.geometry} material={materials['Color.020']} />
          <mesh name="Scene299_1" geometry={nodes.Scene299_1.geometry} material={materials['Material.148']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/officeDino.glb')
