/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/scene.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Scene(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('./models/scene.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="saa" scale={0.217}>
          <group name="Sketchfab_model005" position={[2.059, 1.229, 3.851]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.001}>
            <group name="bb72ba8bbfb44c1699d0d806248193fafbx" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Object_2">
                <group name="RootNode001">
                  <group name="Cloner">
                    <group name="Plane_0" position={[-2.812, 95.99, -143.396]} rotation={[0.433, -0.027, -0.207]}>
                      <mesh name="Plane_0_Mat1_0" geometry={nodes.Plane_0_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_1" position={[5.35, 82.196, -179.64]} rotation={[0.65, 0.11, -0.391]}>
                      <mesh name="Plane_1_Mat1_0" geometry={nodes.Plane_1_Mat1_0.geometry} material={materials['Mat.1']} position={[0, 0, 0]} />
                    </group>
                    <group name="Plane_10" position={[-9.229, 82.404, -162.238]} rotation={[0.447, 0.123, -0.281]}>
                      <mesh name="Plane_10_Mat1_0" geometry={nodes.Plane_10_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_11" position={[13.556, 83.523, -162.787]} rotation={[0.375, 0.016, -0.273]}>
                      <mesh name="Plane_11_Mat1_0" geometry={nodes.Plane_11_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_12" position={[27.686, 89.401, -151.032]} rotation={[0.568, 0.251, -0.386]}>
                      <mesh name="Plane_12_Mat1_0" geometry={nodes.Plane_12_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_13" position={[-10.876, 74.717, -103.5]} rotation={[0.361, 0.368, -0.13]}>
                      <mesh name="Plane_13_Mat1_0" geometry={nodes.Plane_13_Mat1_0.geometry} material={materials['Mat.1']} position={[0, 0, 0]} />
                    </group>
                    <group name="Plane_14" position={[-9.882, 86.725, -78.181]} rotation={[0.53, 0.234, -0.117]}>
                      <mesh name="Plane_14_Mat1_0" geometry={nodes.Plane_14_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_15" position={[-72.954, 125.354, -173.314]} rotation={[0.573, 0.208, -0.495]}>
                      <mesh name="Plane_15_Mat1_0" geometry={nodes.Plane_15_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_16" position={[-3.234, 156.132, -100.524]} rotation={[0.583, 0.021, -0.254]}>
                      <mesh name="Plane_16_Mat1_0" geometry={nodes.Plane_16_Mat1_0.geometry} material={materials['Mat.1']} position={[0, 0, 0]} />
                    </group>
                    <group name="Plane_17" position={[-35.252, 98.674, -160.219]} rotation={[0.648, 0.292, -0.493]}>
                      <mesh name="Plane_17_Mat1_0" geometry={nodes.Plane_17_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_18" position={[13.774, 92.585, -123.962]} rotation={[0.626, 0.292, -0.351]}>
                      <mesh name="Plane_18_Mat1_0" geometry={nodes.Plane_18_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_19" position={[1.404, 98.154, -77.847]} rotation={[0.375, 0.308, -0.114]}>
                      <mesh name="Plane_19_Mat1_0" geometry={nodes.Plane_19_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_2" position={[19.861, 149.588, -131.123]} rotation={[0.708, 0.236, -0.5]}>
                      <mesh name="Plane_2_Mat1_0" geometry={nodes.Plane_2_Mat1_0.geometry} material={materials['Mat.1']} position={[-0.001, 0, 0]} />
                    </group>
                    <group name="Plane_20" position={[-22.12, 31.888, -117.514]} rotation={[0.418, 0.011, -0.005]}>
                      <mesh name="Plane_20_Mat1_0" geometry={nodes.Plane_20_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_21" position={[-30.725, 101.488, -178.666]} rotation={[0.557, 0.202, -0.464]}>
                      <mesh name="Plane_21_Mat1_0" geometry={nodes.Plane_21_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_22" position={[-59.826, 82.192, -165.489]} rotation={[0.571, 0.06, -0.297]}>
                      <mesh name="Plane_22_Mat1_0" geometry={nodes.Plane_22_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_23" position={[-3.979, 71.929, -198.448]} rotation={[0.676, 0.232, -0.516]}>
                      <mesh name="Plane_23_Mat1_0" geometry={nodes.Plane_23_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_24" position={[2.285, 54.208, -181.502]} rotation={[0.699, 0.082, -0.318]}>
                      <mesh name="Plane_24_Mat1_0" geometry={nodes.Plane_24_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_25" position={[-24.552, 100.884, -133.482]} rotation={[0.738, 0.2, -0.374]}>
                      <mesh name="Plane_25_Mat1_0" geometry={nodes.Plane_25_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_26" position={[2.678, 26.027, -125.985]} rotation={[0.66, 0.042, -0.052]}>
                      <mesh name="Plane_26_Mat1_0" geometry={nodes.Plane_26_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_27" position={[-3.582, 148.503, -118.661]} rotation={[0.639, 0.004, -0.271]}>
                      <mesh name="Plane_27_Mat1_0" geometry={nodes.Plane_27_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_28" position={[14.896, 127.902, -167.03]} rotation={[0.65, 0.216, -0.497]}>
                      <mesh name="Plane_28_Mat1_0" geometry={nodes.Plane_28_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_29" position={[8.262, 99.637, -93.873]} rotation={[0.407, 0.331, -0.181]}>
                      <mesh name="Plane_29_Mat1_0" geometry={nodes.Plane_29_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_3" position={[23.243, 120.612, -121.991]} rotation={[0.444, 0.114, -0.259]}>
                      <mesh name="Plane_3_Mat1_0" geometry={nodes.Plane_3_Mat1_0.geometry} material={materials['Mat.1']} position={[0.001, 0, 0]} />
                    </group>
                    <group name="Plane_30" position={[22.116, 136.318, -149.507]} rotation={[0.636, 0.288, -0.51]}>
                      <mesh name="Plane_30_Mat1_0" geometry={nodes.Plane_30_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_31" position={[18.091, 144.479, -163.755]} rotation={[0.642, 0.109, -0.446]}>
                      <mesh name="Plane_31_Mat1_0" geometry={nodes.Plane_31_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_32" position={[28.333, 121.36, -149.28]} rotation={[0.425, 0.022, -0.293]}>
                      <mesh name="Plane_32_Mat1_0" geometry={nodes.Plane_32_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_33" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_33_Mat1_0" geometry={nodes.Plane_33_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_34" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_34_Mat1_0" geometry={nodes.Plane_34_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_35" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_35_Mat1_0" geometry={nodes.Plane_35_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_36" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_36_Mat1_0" geometry={nodes.Plane_36_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_37" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_37_Mat1_0" geometry={nodes.Plane_37_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_38" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_38_Mat1_0" geometry={nodes.Plane_38_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_39" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_39_Mat1_0" geometry={nodes.Plane_39_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_4" position={[-7.041, 130.093, -85.642]} rotation={[0.447, 0.168, -0.206]}>
                      <mesh name="Plane_4_Mat1_0" geometry={nodes.Plane_4_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_40" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_40_Mat1_0" geometry={nodes.Plane_40_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_41" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_41_Mat1_0" geometry={nodes.Plane_41_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_42" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_42_Mat1_0" geometry={nodes.Plane_42_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_43" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_43_Mat1_0" geometry={nodes.Plane_43_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_44" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_44_Mat1_0" geometry={nodes.Plane_44_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_45" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_45_Mat1_0" geometry={nodes.Plane_45_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_46" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_46_Mat1_0" geometry={nodes.Plane_46_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_47" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_47_Mat1_0" geometry={nodes.Plane_47_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_48" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_48_Mat1_0" geometry={nodes.Plane_48_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_49" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_49_Mat1_0" geometry={nodes.Plane_49_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_5" position={[8.164, 141.892, -110.003]} rotation={[0.504, 0.187, -0.31]}>
                      <mesh name="Plane_5_Mat1_0" geometry={nodes.Plane_5_Mat1_0.geometry} material={materials['Mat.1']} position={[-0.001, 0, 0]} />
                    </group>
                    <group name="Plane_50" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_50_Mat1_0" geometry={nodes.Plane_50_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_51" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_51_Mat1_0" geometry={nodes.Plane_51_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_52" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_52_Mat1_0" geometry={nodes.Plane_52_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_53" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_53_Mat1_0" geometry={nodes.Plane_53_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_54" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_54_Mat1_0" geometry={nodes.Plane_54_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_55" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_55_Mat1_0" geometry={nodes.Plane_55_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_56" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_56_Mat1_0" geometry={nodes.Plane_56_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_57" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_57_Mat1_0" geometry={nodes.Plane_57_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_58" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_58_Mat1_0" geometry={nodes.Plane_58_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_59" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_59_Mat1_0" geometry={nodes.Plane_59_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_6" position={[-82.618, 144.114, -147.036]} rotation={[0.645, 0.069, -0.403]}>
                      <mesh name="Plane_6_Mat1_0" geometry={nodes.Plane_6_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_60" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_60_Mat1_0" geometry={nodes.Plane_60_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_61" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_61_Mat1_0" geometry={nodes.Plane_61_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_62" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_62_Mat1_0" geometry={nodes.Plane_62_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_63" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_63_Mat1_0" geometry={nodes.Plane_63_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_64" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_64_Mat1_0" geometry={nodes.Plane_64_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_65" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_65_Mat1_0" geometry={nodes.Plane_65_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_7" position={[37.997, 94.418, -122.842]} rotation={[0.411, 0.311, -0.236]}>
                      <mesh name="Plane_7_Mat1_0" geometry={nodes.Plane_7_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_8" position={[-18.231, 68.121, -87.229]} rotation={[0.668, 0.021, -0.018]}>
                      <mesh name="Plane_8_Mat1_0" geometry={nodes.Plane_8_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_9" position={[47.453, 62.907, -113.816]} rotation={[0.754, 0.235, -0.3]}>
                      <mesh name="Plane_9_Mat1_0" geometry={nodes.Plane_9_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                  </group>
                  <group name="Emitter" rotation={[0.692, 0, 0]} />
                </group>
              </group>
            </group>
          </group>
          <group name="node_33212657_deac_4e36_aed6_dd36c34f55e2_mesh0001" position={[-1.451, 4.531, -0.305]} rotation={[2.808, -0.414, -0.151]} scale={0.697}>
            <mesh name="geometry_f03c6bd1_58eb_4001_bf58_bcabf85dabf8001" geometry={nodes.geometry_f03c6bd1_58eb_4001_bf58_bcabf85dabf8001.geometry} material={materials['Material.013']} />
            <mesh name="geometry_f03c6bd1_58eb_4001_bf58_bcabf85dabf8001_1" geometry={nodes.geometry_f03c6bd1_58eb_4001_bf58_bcabf85dabf8001_1.geometry} material={materials['Material.007']} />
          </group>
          <group name="Sketchfab_model010" position={[1.734, 3.646, -2.066]} rotation={[-Math.PI / 2, 0, 0]} scale={5.264}>
            <group name="root005">
              <group name="GLTF_SceneRootNode005" rotation={[Math.PI / 2, 0, 0]}>
                <group name="root_0">
                  <group name="node_id214_1" position={[-0.027, -0.216, 0.545]} rotation={[0, 0.236, 0]} scale={0.004} />
                </group>
              </group>
            </group>
          </group>
          <group name="Sketchfab_model" position={[1.222, 2.48, 0.691]} rotation={[-Math.PI / 2, 0, -0.542]} scale={0.001}>
            <group name="root">
              <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
                <group name="BluffTitler_Show_0">
                  <group name="BluffTitler_Camera_Layer_1_1" />
                  <group name="BluffTitler_Text_Layer_3_2">
                    <group name="Letter_I_10" position={[-55.877, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.Material} />
                    </group>
                    <group name="Letter_I_11" position={[-27.938, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.Material} />
                    </group>
                    <group name="Letter_I_12" position={[0, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.Material} />
                    </group>
                    <group name="Letter_I_13" position={[27.939, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.Material} />
                    </group>
                    <group name="Letter_I_14" position={[55.877, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.Material} />
                    </group>
                    <group name="Letter_I_15" position={[83.815, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.Material} />
                    </group>
                    <group name="Letter_I_16" position={[111.754, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.Material} />
                    </group>
                    <group name="Letter_I_17" position={[139.692, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials.Material} />
                    </group>
                    <group name="Letter_I_18" position={[167.63, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials.Material} />
                    </group>
                    <group name="Letter_I_19" position={[195.569, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_39" geometry={nodes.Object_39.geometry} material={materials.Material} />
                    </group>
                    <group name="Letter_I_20" position={[223.507, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials.Material} />
                    </group>
                    <group name="Letter_I_21" position={[251.445, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_43" geometry={nodes.Object_43.geometry} material={materials.Material} />
                    </group>
                    <group name="Letter_I_3" position={[-251.445, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Material} />
                    </group>
                    <group name="Letter_I_4" position={[-223.506, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Material} />
                    </group>
                    <group name="Letter_I_5" position={[-195.568, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.Material} />
                    </group>
                    <group name="Letter_I_6" position={[-167.63, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.Material} />
                    </group>
                    <group name="Letter_I_7" position={[-139.691, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.Material} />
                    </group>
                    <group name="Letter_I_8" position={[-111.753, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.Material} />
                    </group>
                    <group name="Letter_I_9" position={[-83.815, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.Material} />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
          <group name="Sketchfab_model001" position={[-0.665, 2.48, 0.608]} rotation={[-Math.PI / 2, 0, 0.859]} scale={0.001}>
            <group name="root001">
              <group name="GLTF_SceneRootNode001" rotation={[Math.PI / 2, 0, 0]}>
                <group name="BluffTitler_Show_0001">
                  <group name="BluffTitler_Camera_Layer_1_1001" />
                  <group name="BluffTitler_Text_Layer_3_2001">
                    <group name="Letter_I_10001" position={[-55.877, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_21001" geometry={nodes.Object_21001.geometry} material={materials.Material} position={[0, -0.008, 0]} />
                    </group>
                    <group name="Letter_I_11001" position={[-27.938, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_23001" geometry={nodes.Object_23001.geometry} material={materials.Material} position={[0, -0.008, 0]} />
                    </group>
                    <group name="Letter_I_12001" position={[0, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_25001" geometry={nodes.Object_25001.geometry} material={materials.Material} position={[0, -0.008, 0]} />
                    </group>
                    <group name="Letter_I_13001" position={[27.938, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_27001" geometry={nodes.Object_27001.geometry} material={materials.Material} position={[0, -0.008, 0]} />
                    </group>
                    <group name="Letter_I_14001" position={[55.877, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_29001" geometry={nodes.Object_29001.geometry} material={materials.Material} position={[0, -0.008, 0]} />
                    </group>
                    <group name="Letter_I_15001" position={[83.815, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_31001" geometry={nodes.Object_31001.geometry} material={materials.Material} position={[0, -0.008, 0]} />
                    </group>
                    <group name="Letter_I_16001" position={[111.753, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_33001" geometry={nodes.Object_33001.geometry} material={materials.Material} position={[0, -0.008, 0]} />
                    </group>
                    <group name="Letter_I_17001" position={[139.692, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_35001" geometry={nodes.Object_35001.geometry} material={materials.Material} position={[0, -0.008, 0]} />
                    </group>
                    <group name="Letter_I_18001" position={[167.63, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_37001" geometry={nodes.Object_37001.geometry} material={materials.Material} position={[0, -0.008, 0]} />
                    </group>
                    <group name="Letter_I_19001" position={[195.568, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_39001" geometry={nodes.Object_39001.geometry} material={materials.Material} position={[0, -0.008, 0]} />
                    </group>
                    <group name="Letter_I_20001" position={[223.507, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_41001" geometry={nodes.Object_41001.geometry} material={materials.Material} position={[0, -0.008, 0]} />
                    </group>
                    <group name="Letter_I_21001" position={[251.445, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_43001" geometry={nodes.Object_43001.geometry} material={materials.Material} position={[0, -0.008, 0]} />
                    </group>
                    <group name="Letter_I_3001" position={[-251.445, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_7001" geometry={nodes.Object_7001.geometry} material={materials.Material} position={[0, -0.008, 0]} />
                    </group>
                    <group name="Letter_I_4001" position={[-223.507, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_9003" geometry={nodes.Object_9003.geometry} material={materials.Material} position={[0, -0.008, 0]} />
                    </group>
                    <group name="Letter_I_5001" position={[-195.568, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_11003" geometry={nodes.Object_11003.geometry} material={materials.Material} position={[0, -0.008, 0]} />
                    </group>
                    <group name="Letter_I_6001" position={[-167.63, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_13001" geometry={nodes.Object_13001.geometry} material={materials.Material} position={[0, -0.008, 0]} />
                    </group>
                    <group name="Letter_I_7001" position={[-139.692, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_15001" geometry={nodes.Object_15001.geometry} material={materials.Material} position={[0, -0.008, 0]} />
                    </group>
                    <group name="Letter_I_8001" position={[-111.753, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_17001" geometry={nodes.Object_17001.geometry} material={materials.Material} position={[0, -0.008, 0]} />
                    </group>
                    <group name="Letter_I_9001" position={[-83.815, -1.172, -500]} scale={[1, 0.051, 0.253]}>
                      <mesh name="Object_19001" geometry={nodes.Object_19001.geometry} material={materials.Material} position={[0, -0.008, 0]} />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
          <group name="Sketchfab_model002" position={[2.612, 1.802, -1.513]} rotation={[-Math.PI / 2, 0, 0]} scale={0.25} />
          <group name="ea34c3e318124a9d9fbe7a47f664abc9fbx" position={[2.612, 1.802, -1.513]} scale={0.003} />
          <group name="RootNode" position={[2.612, 1.802, -1.513]} scale={0.003} />
          <group name="Machine_Done" position={[2.612, 1.802, -1.513]} scale={0.003} />
          <group name="pCylinder10" position={[2.612, 1.802, -1.513]} scale={0.003} />
          <group name="pCube53" position={[2.612, 1.802, -1.513]} scale={0.003} />
          <group name="pCube52" position={[2.612, 1.802, -1.513]} scale={0.003} />
          <group name="pCube51" position={[2.612, 1.802, -1.513]} scale={0.003} />
          <group name="pCube50" position={[2.612, 1.802, -1.513]} scale={0.003} />
          <group name="pCube49" position={[2.612, 1.802, -1.513]} scale={0.003} />
          <group name="pCube49_lambert1_0" position={[2.612, 1.617, -1.513]} rotation={[0, 0.994, 0]} scale={0.003}>
            <mesh name="pCube49_lambert1_0_1" geometry={nodes.pCube49_lambert1_0_1.geometry} material={materials.lambert1} />
            <mesh name="pCube49_lambert1_0_2" geometry={nodes.pCube49_lambert1_0_2.geometry} material={materials['Material.001']} />
          </group>
          <group name="pCylinder1" position={[2.612, 1.802, -1.513]} scale={0.003} />
          <group name="polySurface3" position={[2.612, 1.802, -1.513]} scale={0.003} />
          <group name="polySurface2" position={[2.612, 1.802, -1.513]} scale={0.003} />
          <group name="pCylinder2" position={[2.612, 1.802, -1.513]} scale={0.003} />
          <group name="pCylinder3" position={[2.612, 1.802, -1.513]} scale={0.003} />
          <group name="pCylinder5" position={[2.612, 1.802, -1.513]} scale={0.003} />
          <group name="pCylinder4" position={[2.612, 1.802, -1.513]} scale={0.003} />
          <group name="pCylinder6" position={[2.612, 1.802, -1.513]} scale={0.003} />
          <group name="pCylinder7" position={[2.612, 1.802, -1.513]} scale={0.003} />
          <group name="pCylinder8" position={[2.612, 1.802, -1.513]} scale={0.003} />
          <group name="pCube54" position={[2.612, 1.802, -1.513]} scale={0.003} />
          <group name="pCylinder9" position={[2.612, 1.802, -1.513]} scale={0.003} />
          <group name="Sketchfab_model003" position={[2.095, 1.33, 3.647]} rotation={[-Math.PI / 2, 0, 1.712]} />
          <group name="root002" position={[2.095, 1.33, 3.647]} rotation={[-Math.PI / 2, 0, 1.712]} />
          <group name="GLTF_SceneRootNode002" position={[2.095, 1.33, 3.647]} rotation={[-Math.PI, 1.43, -Math.PI]} />
          <group name="SM_MovingHead_Base_3" position={[2.095, 1.33, 3.647]} rotation={[-Math.PI, 1.43, -Math.PI]} scale={0.01} />
          <group name="SM_MovingHead_Yoke_2" position={[2.095, 1.33, 3.647]} rotation={[0, 0.927, 0]} scale={0.01} />
          <group name="SM_MovingHead_Head_1" position={[2.095, 1.617, 3.647]} rotation={[-1.03, 0.601, 0.755]} scale={0.01} />
          <group name="SM_MovingHead_Lens_0" position={[2.095, 1.616, 3.647]} rotation={[-1.03, 0.601, 0.755]} scale={0.01} />
          <group name="Sketchfab_model004" position={[-1.59, 1.33, 3.647]} rotation={[-Math.PI / 2, 0, -0.279]} />
          <group name="root003" position={[-1.59, 1.33, 3.647]} rotation={[-Math.PI / 2, 0, -0.279]} />
          <group name="GLTF_SceneRootNode003" position={[-1.59, 1.33, 3.647]} rotation={[0, -0.279, 0]} />
          <group name="SM_MovingHead_Base_3001" position={[-1.59, 1.33, 3.647]} rotation={[0, -0.279, 0]} scale={0.01} />
          <group name="Object_4001" position={[-1.645, 1.33, 3.719]} rotation={[0, -0.279, 0]} scale={0.01}>
            <mesh name="Object_0003" geometry={nodes.Object_0003.geometry} material={materials['MI_MovingHead.001']} />
            <mesh name="Object_0003_1" geometry={nodes.Object_0003_1.geometry} material={materials['MI_MovingHead.003']} />
            <mesh name="Object_0003_2" geometry={nodes.Object_0003_2.geometry} material={materials['MI_MovingHead.002']} />
            <mesh name="Object_0003_3" geometry={nodes.Object_0003_3.geometry} material={materials['M_LensDefault_Master.001']} />
          </group>
          <group name="SM_MovingHead_Yoke_2001" position={[-1.59, 1.33, 3.647]} rotation={[0, -1.064, 0]} scale={0.01} />
          <group name="SM_MovingHead_Head_1001" position={[-1.59, 1.617, 3.647]} rotation={[-1.119, -0.667, -0.905]} scale={0.01} />
          <group name="SM_MovingHead_Lens_0001" position={[-1.59, 1.616, 3.647]} rotation={[-1.119, -0.667, -0.905]} scale={0.01} />
          <group name="Object_4002" position={[2.144, 1.33, 3.713]} rotation={[0, 1.492, 0]} scale={0.01}>
            <mesh name="Object_0004" geometry={nodes.Object_0004.geometry} material={materials['MI_MovingHead.001']} />
            <mesh name="Object_0004_1" geometry={nodes.Object_0004_1.geometry} material={materials['MI_MovingHead.003']} />
            <mesh name="Object_0004_2" geometry={nodes.Object_0004_2.geometry} material={materials['MI_MovingHead.002']} />
            <mesh name="Object_0004_3" geometry={nodes.Object_0004_3.geometry} material={materials['M_LensDefault_Master.001']} />
          </group>
          <group name="Sketchfab_model006" position={[-1.434, 1.229, 3.851]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.001}>
            <group name="bb72ba8bbfb44c1699d0d806248193fafbx001" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Object_2001">
                <group name="RootNode002">
                  <group name="Cloner001">
                    <group name="Plane_0001" position={[-2.812, 95.991, -143.396]} rotation={[0.433, -0.027, -0.207]}>
                      <mesh name="Plane_0_Mat1_0001" geometry={nodes.Plane_0_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_1001" position={[5.35, 82.197, -179.64]} rotation={[0.65, 0.11, -0.391]}>
                      <mesh name="Plane_1_Mat1_0001" geometry={nodes.Plane_1_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_10001" position={[-9.229, 82.404, -162.238]} rotation={[0.447, 0.123, -0.281]}>
                      <mesh name="Plane_10_Mat1_0001" geometry={nodes.Plane_10_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_11001" position={[13.557, 83.523, -162.787]} rotation={[0.375, 0.016, -0.273]}>
                      <mesh name="Plane_11_Mat1_0001" geometry={nodes.Plane_11_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_12001" position={[27.686, 89.401, -151.032]} rotation={[0.568, 0.251, -0.386]}>
                      <mesh name="Plane_12_Mat1_0001" geometry={nodes.Plane_12_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_13001" position={[-10.876, 74.717, -103.5]} rotation={[0.361, 0.368, -0.13]}>
                      <mesh name="Plane_13_Mat1_0001" geometry={nodes.Plane_13_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_14001" position={[-9.882, 86.725, -78.181]} rotation={[0.53, 0.234, -0.117]}>
                      <mesh name="Plane_14_Mat1_0001" geometry={nodes.Plane_14_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_15001" position={[-72.954, 125.355, -173.314]} rotation={[0.573, 0.208, -0.495]}>
                      <mesh name="Plane_15_Mat1_0001" geometry={nodes.Plane_15_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_16001" position={[-3.234, 156.132, -100.524]} rotation={[0.583, 0.021, -0.254]}>
                      <mesh name="Plane_16_Mat1_0001" geometry={nodes.Plane_16_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_17001" position={[-35.252, 98.675, -160.219]} rotation={[0.648, 0.292, -0.493]}>
                      <mesh name="Plane_17_Mat1_0001" geometry={nodes.Plane_17_Mat1_0001.geometry} material={materials['Mat.1']} position={[0, -0.001, 0]} />
                    </group>
                    <group name="Plane_18001" position={[13.774, 92.586, -123.962]} rotation={[0.626, 0.292, -0.351]}>
                      <mesh name="Plane_18_Mat1_0001" geometry={nodes.Plane_18_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_19001" position={[1.404, 98.154, -77.847]} rotation={[0.375, 0.308, -0.114]}>
                      <mesh name="Plane_19_Mat1_0001" geometry={nodes.Plane_19_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_2001" position={[19.861, 149.589, -131.123]} rotation={[0.708, 0.236, -0.5]}>
                      <mesh name="Plane_2_Mat1_0001" geometry={nodes.Plane_2_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_20001" position={[-22.12, 31.888, -117.514]} rotation={[0.418, 0.011, -0.005]}>
                      <mesh name="Plane_20_Mat1_0001" geometry={nodes.Plane_20_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_21001" position={[-30.725, 101.488, -178.666]} rotation={[0.557, 0.202, -0.464]}>
                      <mesh name="Plane_21_Mat1_0001" geometry={nodes.Plane_21_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_22001" position={[-59.826, 82.193, -165.489]} rotation={[0.571, 0.06, -0.297]}>
                      <mesh name="Plane_22_Mat1_0001" geometry={nodes.Plane_22_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_23001" position={[-3.979, 71.929, -198.448]} rotation={[0.676, 0.232, -0.516]}>
                      <mesh name="Plane_23_Mat1_0001" geometry={nodes.Plane_23_Mat1_0001.geometry} material={materials['Mat.1']} position={[0, 0.001, 0]} />
                    </group>
                    <group name="Plane_24001" position={[2.285, 54.209, -181.502]} rotation={[0.699, 0.082, -0.318]}>
                      <mesh name="Plane_24_Mat1_0001" geometry={nodes.Plane_24_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_25001" position={[-24.551, 100.884, -133.482]} rotation={[0.738, 0.2, -0.374]}>
                      <mesh name="Plane_25_Mat1_0001" geometry={nodes.Plane_25_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_26001" position={[2.678, 26.028, -125.985]} rotation={[0.66, 0.042, -0.052]}>
                      <mesh name="Plane_26_Mat1_0001" geometry={nodes.Plane_26_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_27001" position={[-3.582, 148.503, -118.661]} rotation={[0.639, 0.004, -0.271]}>
                      <mesh name="Plane_27_Mat1_0001" geometry={nodes.Plane_27_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_28001" position={[14.897, 127.903, -167.03]} rotation={[0.65, 0.216, -0.497]}>
                      <mesh name="Plane_28_Mat1_0001" geometry={nodes.Plane_28_Mat1_0001.geometry} material={materials['Mat.1']} position={[0, 0, 0]} />
                    </group>
                    <group name="Plane_29001" position={[8.262, 99.638, -93.873]} rotation={[0.407, 0.331, -0.181]}>
                      <mesh name="Plane_29_Mat1_0001" geometry={nodes.Plane_29_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_3001" position={[23.244, 120.612, -121.991]} rotation={[0.444, 0.114, -0.259]}>
                      <mesh name="Plane_3_Mat1_0001" geometry={nodes.Plane_3_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_30001" position={[22.117, 136.319, -149.507]} rotation={[0.636, 0.288, -0.51]}>
                      <mesh name="Plane_30_Mat1_0001" geometry={nodes.Plane_30_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_31001" position={[18.091, 144.479, -163.755]} rotation={[0.642, 0.109, -0.446]}>
                      <mesh name="Plane_31_Mat1_0001" geometry={nodes.Plane_31_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_32001" position={[28.333, 121.361, -149.28]} rotation={[0.425, 0.022, -0.293]}>
                      <mesh name="Plane_32_Mat1_0001" geometry={nodes.Plane_32_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_33001" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_33_Mat1_0001" geometry={nodes.Plane_33_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_34001" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_34_Mat1_0001" geometry={nodes.Plane_34_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_35001" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_35_Mat1_0001" geometry={nodes.Plane_35_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_36001" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_36_Mat1_0001" geometry={nodes.Plane_36_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_37001" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_37_Mat1_0001" geometry={nodes.Plane_37_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_38001" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_38_Mat1_0001" geometry={nodes.Plane_38_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_39001" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_39_Mat1_0001" geometry={nodes.Plane_39_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_4001" position={[-7.041, 130.094, -85.642]} rotation={[0.447, 0.168, -0.206]}>
                      <mesh name="Plane_4_Mat1_0001" geometry={nodes.Plane_4_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_40001" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_40_Mat1_0001" geometry={nodes.Plane_40_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_41001" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_41_Mat1_0001" geometry={nodes.Plane_41_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_42001" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_42_Mat1_0001" geometry={nodes.Plane_42_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_43001" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_43_Mat1_0001" geometry={nodes.Plane_43_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_44001" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_44_Mat1_0001" geometry={nodes.Plane_44_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_45001" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_45_Mat1_0001" geometry={nodes.Plane_45_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_46001" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_46_Mat1_0001" geometry={nodes.Plane_46_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_47001" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_47_Mat1_0001" geometry={nodes.Plane_47_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_48001" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_48_Mat1_0001" geometry={nodes.Plane_48_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_49001" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_49_Mat1_0001" geometry={nodes.Plane_49_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_5001" position={[8.164, 141.892, -110.003]} rotation={[0.504, 0.187, -0.31]}>
                      <mesh name="Plane_5_Mat1_0001" geometry={nodes.Plane_5_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_50001" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_50_Mat1_0001" geometry={nodes.Plane_50_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_51001" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_51_Mat1_0001" geometry={nodes.Plane_51_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_52001" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_52_Mat1_0001" geometry={nodes.Plane_52_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_53001" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_53_Mat1_0001" geometry={nodes.Plane_53_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_54001" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_54_Mat1_0001" geometry={nodes.Plane_54_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_55001" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_55_Mat1_0001" geometry={nodes.Plane_55_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_56001" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_56_Mat1_0001" geometry={nodes.Plane_56_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_57001" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_57_Mat1_0001" geometry={nodes.Plane_57_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_58001" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_58_Mat1_0001" geometry={nodes.Plane_58_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_59001" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_59_Mat1_0001" geometry={nodes.Plane_59_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_6001" position={[-82.617, 144.115, -147.035]} rotation={[0.645, 0.069, -0.403]}>
                      <mesh name="Plane_6_Mat1_0001" geometry={nodes.Plane_6_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_60001" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_60_Mat1_0001" geometry={nodes.Plane_60_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_61001" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_61_Mat1_0001" geometry={nodes.Plane_61_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_62001" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_62_Mat1_0001" geometry={nodes.Plane_62_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_63001" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_63_Mat1_0001" geometry={nodes.Plane_63_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_64001" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_64_Mat1_0001" geometry={nodes.Plane_64_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_65001" rotation={[0.692, 0, 0]}>
                      <mesh name="Plane_65_Mat1_0001" geometry={nodes.Plane_65_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_7001" position={[37.998, 94.418, -122.842]} rotation={[0.411, 0.311, -0.236]}>
                      <mesh name="Plane_7_Mat1_0001" geometry={nodes.Plane_7_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_8001" position={[-18.231, 68.121, -87.229]} rotation={[0.668, 0.021, -0.018]}>
                      <mesh name="Plane_8_Mat1_0001" geometry={nodes.Plane_8_Mat1_0001.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Plane_9001" position={[47.453, 62.907, -113.816]} rotation={[0.754, 0.235, -0.3]}>
                      <mesh name="Plane_9_Mat1_0001" geometry={nodes.Plane_9_Mat1_0001.geometry} material={materials['Mat.1']} position={[0, -0.001, 0]} />
                    </group>
                  </group>
                  <group name="Emitter001" rotation={[0.692, 0, 0]} />
                </group>
              </group>
            </group>
          </group>
          <group name="node_438b64c4_089f_4a5f_8090_789b6782eff0" position={[-2.856, 3.276, -3.652]} rotation={[Math.PI / 2, 0, 2.706]} scale={[3.339, 1.875, 1.875]} />
          <group name="node_1c880b5b_d49e_4b2d_a593_cb85239bf439" position={[-2.883, 3.276, -3.712]} rotation={[Math.PI / 2, 0, -0.435]} scale={0.654} />
          <group name="node_89ea1a5a_c5cc_40f2_a3ba_1d9ae86a321c" position={[2.908, 5.811, 2.624]} rotation={[-2.763, 0.912, -2.454]} />
          <group name="node_af4bf03e_50f9_4b43_8d48_3b5badb8f34e_mesh0" position={[0.288, 1.35, 0.274]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh name="geometry_cd4b5ef0_ff90_4229_bcf7_d51b02b456c6" geometry={nodes.geometry_cd4b5ef0_ff90_4229_bcf7_d51b02b456c6.geometry} material={materials['mat_15.002']} />
            <mesh name="geometry_cd4b5ef0_ff90_4229_bcf7_d51b02b456c6_1" geometry={nodes.geometry_cd4b5ef0_ff90_4229_bcf7_d51b02b456c6_1.geometry} material={materials['Material.009']} />
          </group>
          <group name="node_ba6c5aab_e43d_4245_a409_913c5825aad5" position={[-2.625, 3.276, -3.156]} rotation={[Math.PI / 2, 0, -0.435]} scale={0.654} />
          <group name="node_2d3306f9_b681_4efa_8633_91e0b05bf7c2" position={[0.288, -2.249, 0.274]} rotation={[Math.PI / 2, 0, 0]} />
          <group name="node_a2def745_ecdb_4bb7_ac83_1e242e8dc004" position={[0.288, -2.249, 0.274]} rotation={[Math.PI / 2, 0, 0]} />
          <group name="node_72c1c9ce_bcbb_4e55_8fb9_391c09196dcc" position={[0.288, -2.249, 0.274]} rotation={[Math.PI / 2, 0, 0]} />
          <group name="All" position={[1.809, 2.634, 2.457]} scale={13.893} />
          <group name="Area" position={[1.048, 5.634, 1.366]} rotation={[-1.058, 0.08, 0.207]} scale={9.408} />
          <group name="Area001" position={[0.302, 6.347, -3.474]} rotation={[-1.985, -0.025, -0.129]} scale={9.408} />
          <group name="first" position={[2.023, 1.77, 1.695]} rotation={[0, -1.22, 0]} scale={0.694}>
            <group name="rig">
              <primitive object={nodes.root_1} />
              <group name="f_1">
                <skinnedMesh name="Mesh001" geometry={nodes.Mesh001.geometry} material={materials.characters} skeleton={nodes.Mesh001.skeleton} />
                <skinnedMesh name="Mesh001_1" geometry={nodes.Mesh001_1.geometry} material={materials.characters} skeleton={nodes.Mesh001_1.skeleton} />
              </group>
            </group>
          </group>
          <group name="character02" position={[1.385, 1.786, 2.047]} rotation={[-Math.PI, 0.132, -Math.PI]} scale={0.643}>
            <group name="rig001">
              <primitive object={nodes.root_2} />
              <group name="m_11">
                <skinnedMesh name="Mesh002" geometry={nodes.Mesh002.geometry} material={materials['characters.001']} skeleton={nodes.Mesh002.skeleton} />
                <skinnedMesh name="Mesh002_1" geometry={nodes.Mesh002_1.geometry} material={materials.characters} skeleton={nodes.Mesh002_1.skeleton} />
              </group>
            </group>
          </group>
          <group name="Character03" position={[0.477, 1.983, -0.11]} scale={0.531}>
            <group name="rig002" scale={1.248}>
              <primitive object={nodes.root_3} />
              <group name="m_7">
                <skinnedMesh name="Mesh003" geometry={nodes.Mesh003.geometry} material={materials['characters.002']} skeleton={nodes.Mesh003.skeleton} />
                <skinnedMesh name="Mesh003_1" geometry={nodes.Mesh003_1.geometry} material={materials['characters.002']} skeleton={nodes.Mesh003_1.skeleton} />
              </group>
            </group>
          </group>
          <group name="40M" position={[0.209, 1.449, 3.06]} scale={1.282}>
            <mesh name="Text001" geometry={nodes.Text001.geometry} material={materials['Material.028']} position={[0, 0.462, 0.402]} rotation={[Math.PI / 2, 0, 0]} scale={[1.186, 0.872, 1.186]} />
          </group>
          <group name="CHARACTER04" position={[-1.45, 1.655, -1.967]} rotation={[0, -1.195, 0]} scale={0.688}>
            <group name="rig003">
              <primitive object={nodes.root_4} />
              <group name="m_12">
                <skinnedMesh name="Mesh004" geometry={nodes.Mesh004.geometry} material={materials['characters.002']} skeleton={nodes.Mesh004.skeleton} />
                <skinnedMesh name="Mesh004_1" geometry={nodes.Mesh004_1.geometry} material={materials['characters.002']} skeleton={nodes.Mesh004_1.skeleton} />
              </group>
            </group>
          </group>
          <group name="CHARACTER05" position={[-2.06, 1.656, -1.48]} rotation={[-Math.PI, 0.607, -Math.PI]} scale={0.639}>
            <group name="rig004" position={[-0.034, -0.013, 0.054]} rotation={[-0.157, 0, -0.063]}>
              <primitive object={nodes.root_5} />
              <group name="m_6">
                <skinnedMesh name="Mesh005" geometry={nodes.Mesh005.geometry} material={materials['characters.002']} skeleton={nodes.Mesh005.skeleton} />
                <skinnedMesh name="Mesh005_1" geometry={nodes.Mesh005_1.geometry} material={materials['characters.002']} skeleton={nodes.Mesh005_1.skeleton} />
              </group>
              <skinnedMesh name="node_aacfec3d_ae09_46b7_8848_238e322581a0_mesh0" geometry={nodes.node_aacfec3d_ae09_46b7_8848_238e322581a0_mesh0.geometry} material={materials['mat_12.002']} skeleton={nodes.node_aacfec3d_ae09_46b7_8848_238e322581a0_mesh0.skeleton} />
              <skinnedMesh name="node_aacfec3d_ae09_46b7_8848_238e322581a0_mesh0001" geometry={nodes.node_aacfec3d_ae09_46b7_8848_238e322581a0_mesh0001.geometry} material={materials['mat_12.002']} skeleton={nodes.node_aacfec3d_ae09_46b7_8848_238e322581a0_mesh0001.skeleton} />
            </group>
          </group>
          <group name="cHARACTER07" position={[0.554, 1.991, 0.745]} rotation={[Math.PI, -0.168, Math.PI]} scale={0.697}>
            <group name="rig005" position={[0.059, -0.006, 0.059]} rotation={[-0.094, -0.133, 0.114]}>
              <primitive object={nodes.root_6} />
              <skinnedMesh name="m_13" geometry={nodes.m_13.geometry} material={materials['characters.002']} skeleton={nodes.m_13.skeleton} />
            </group>
          </group>
          <group name="TRIYA" position={[0.292, 5.527, 0.451]}>
            <mesh name="node_41b68b41_de9a_423d_829f_669dfa469edd_mesh0001" geometry={nodes.node_41b68b41_de9a_423d_829f_669dfa469edd_mesh0001.geometry} material={materials['Material.006']} position={[0, -1.307, 0]} rotation={[Math.PI / 2, 0, -0.309]} scale={0.441} />
            <mesh name="node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0001" geometry={nodes.node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0001.geometry} material={materials['Material.019']} position={[0, -1.307, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.009} />
            <mesh name="node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0002" geometry={nodes.node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0002.geometry} material={materials['Material.018']} position={[0, -1.307, 0]} rotation={[Math.PI / 2, 0, 0]} scale={-0.013} />
            <mesh name="node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0003" geometry={nodes.node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0003.geometry} material={materials['Material.018']} position={[0, -1.307, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.441} />
            <mesh name="node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0004" geometry={nodes.node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0004.geometry} material={materials['Material.019']} position={[0, -1.307, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.44} />
            <mesh name="node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0005" geometry={nodes.node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0005.geometry} material={materials['Material.017']} position={[0, -1.307, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.444} />
            <mesh name="node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0006" geometry={nodes.node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0006.geometry} material={materials['Material.017']} position={[0, -1.307, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.009} />
            <mesh name="node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0007" geometry={nodes.node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0007.geometry} material={materials['Material.018']} position={[0, -1.307, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.011} />
            <mesh name="node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0008" geometry={nodes.node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0008.geometry} material={materials['Material.017']} position={[0, -1.307, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.011} />
            <mesh name="node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0009" geometry={nodes.node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0009.geometry} material={materials['Material.017']} position={[0, -1.307, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.438} />
            <mesh name="node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0010" geometry={nodes.node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0010.geometry} material={materials['Material.017']} position={[0, -1.307, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.017} />
            <mesh name="node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0011" geometry={nodes.node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0011.geometry} material={materials['Material.017']} position={[0, -1.307, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.439} />
            <mesh name="node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0012" geometry={nodes.node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0012.geometry} material={materials['Material.018']} position={[0, -1.307, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.022} />
            <mesh name="node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0013" geometry={nodes.node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0013.geometry} material={materials['Material.019']} position={[0, -1.307, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.375} />
            <mesh name="node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0014" geometry={nodes.node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0014.geometry} material={materials['Material.019']} position={[0, -1.307, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.437} />
            <mesh name="node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0015" geometry={nodes.node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0015.geometry} material={materials['Material.017']} position={[0, -1.307, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.011} />
            <mesh name="node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0016" geometry={nodes.node_5733d94c_5885_45e2_9fac_20a1d05a0a2b_mesh0016.geometry} material={materials['Material.018']} position={[1.435, -3.653, 3.273]} rotation={[-0.963, 1.122, 2.223]} scale={0.358} />
            <mesh name="node_a24b4965_6852_41ba_b37a_60e5ba245102_mesh0001" geometry={nodes.node_a24b4965_6852_41ba_b37a_60e5ba245102_mesh0001.geometry} material={nodes.node_a24b4965_6852_41ba_b37a_60e5ba245102_mesh0001.material} position={[0, 1.307, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.441} />
          </group>
          <group name="TV_07" position={[0.286, 1.874, -3.471]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh name="TV_07_1" geometry={nodes.TV_07_1.geometry} material={materials['Color.002']} />
            <mesh name="TV_07_2" geometry={nodes.TV_07_2.geometry} material={materials['Material.002']} />
          </group>
          <group name="character06" position={[0.54, 1.581, -2.573]} rotation={[Math.PI, 0, Math.PI]} scale={0.684}>
            <group name="rig006" position={[-0.006, -0.138, -0.081]} rotation={[-0.063, -0.039, -0.02]}>
              <primitive object={nodes.root_7} />
              <group name="m_5">
                <skinnedMesh name="Mesh007" geometry={nodes.Mesh007.geometry} material={materials['characters.002']} skeleton={nodes.Mesh007.skeleton} />
                <skinnedMesh name="Mesh007_1" geometry={nodes.Mesh007_1.geometry} material={materials['characters.002']} skeleton={nodes.Mesh007_1.skeleton} />
              </group>
            </group>
          </group>
          <group name="Character08" position={[-0.088, 1.598, -2.603]} rotation={[Math.PI, -0.017, Math.PI]} scale={0.634}>
            <group name="rig007" position={[-0.002, -0.149, -0.016]} rotation={[-0.32, -0.041, 0.006]}>
              <primitive object={nodes.root_8} />
              <group name="f_4">
                <skinnedMesh name="Mesh008" geometry={nodes.Mesh008.geometry} material={materials['characters.002']} skeleton={nodes.Mesh008.skeleton} />
                <skinnedMesh name="Mesh008_1" geometry={nodes.Mesh008_1.geometry} material={materials['characters.002']} skeleton={nodes.Mesh008_1.skeleton} />
              </group>
            </group>
          </group>
          <group name="Character09" position={[3.615, 1.495, 0.113]} rotation={[0, -Math.PI / 2, 0]} scale={0.638}>
            <group name="rig008" position={[0.003, -0.112, 0.199]} rotation={[-0.437, -0.204, 0.01]}>
              <primitive object={nodes.root_9} />
              <group name="f_6">
                <skinnedMesh name="Mesh009" geometry={nodes.Mesh009.geometry} material={materials.characters} skeleton={nodes.Mesh009.skeleton} />
                <skinnedMesh name="Mesh009_1" geometry={nodes.Mesh009_1.geometry} material={materials.characters} skeleton={nodes.Mesh009_1.skeleton} />
              </group>
              <primitive object={nodes.neutral_bone} />
            </group>
          </group>
          <group name="Character10" position={[3.571, 1.491, 0.56]} rotation={[0, -Math.PI / 2, 0]} scale={0.583}>
            <group name="rig009" position={[-0.023, -0.086, 0.117]} rotation={[-0.209, -0.031, -0.053]}>
              <primitive object={nodes.root_10} />
              <group name="f_9">
                <skinnedMesh name="Mesh011" geometry={nodes.Mesh011.geometry} material={materials.characters} skeleton={nodes.Mesh011.skeleton} />
                <skinnedMesh name="Mesh011_1" geometry={nodes.Mesh011_1.geometry} material={materials.characters} skeleton={nodes.Mesh011_1.skeleton} />
              </group>
            </group>
          </group>
          <group name="Character11" position={[-2.931, 1.514, 0.535]} rotation={[0, Math.PI / 2, 0]} scale={0.692}>
            <group name="rig010" position={[-0.002, -0.149, -0.016]} rotation={[-0.32, -0.041, 0.006]}>
              <primitive object={nodes.root_11} />
              <group name="f_8">
                <skinnedMesh name="Mesh012" geometry={nodes.Mesh012.geometry} material={materials['characters.002']} skeleton={nodes.Mesh012.skeleton} />
                <skinnedMesh name="Mesh012_1" geometry={nodes.Mesh012_1.geometry} material={materials['characters.002']} skeleton={nodes.Mesh012_1.skeleton} />
              </group>
            </group>
          </group>
          <group name="Character12" position={[-3.029, 1.508, 0.171]} rotation={[0, Math.PI / 2, 0]} scale={0.643}>
            <group name="rig011" position={[0.003, -0.112, 0.199]} rotation={[-0.437, -0.204, 0.01]}>
              <primitive object={nodes.root_12} />
              <group name="f_7">
                <skinnedMesh name="Mesh013" geometry={nodes.Mesh013.geometry} material={materials['characters.002']} skeleton={nodes.Mesh013.skeleton} />
                <skinnedMesh name="Mesh013_1" geometry={nodes.Mesh013_1.geometry} material={materials['characters.002']} skeleton={nodes.Mesh013_1.skeleton} />
              </group>
            </group>
          </group>
          <group name="Character13" position={[-1.32, 1.793, 1.434]} rotation={[0, 1.226, 0]} scale={0.631}>
            <group name="rig012">
              <primitive object={nodes.root_13} />
              <group name="f_2">
                <skinnedMesh name="Mesh014" geometry={nodes.Mesh014.geometry} material={materials['characters.002']} skeleton={nodes.Mesh014.skeleton} />
                <skinnedMesh name="Mesh014_1" geometry={nodes.Mesh014_1.geometry} material={materials['characters.002']} skeleton={nodes.Mesh014_1.skeleton} />
              </group>
            </group>
          </group>
          <group name="Character14" position={[-1.113, 1.786, 2.266]} rotation={[-Math.PI, 0.267, -Math.PI]} scale={0.692}>
            <group name="rig013" position={[-0.016, -0.005, 0.026]} rotation={[-0.066, -0.091, -0.057]}>
              <primitive object={nodes.root_14} />
              <group name="f_3">
                <skinnedMesh name="Mesh015" geometry={nodes.Mesh015.geometry} material={materials['characters.002']} skeleton={nodes.Mesh015.skeleton} />
                <skinnedMesh name="Mesh015_1" geometry={nodes.Mesh015_1.geometry} material={materials['characters.002']} skeleton={nodes.Mesh015_1.skeleton} />
              </group>
            </group>
          </group>
          <group name="Character16" position={[-0.067, 1.967, 0.218]} rotation={[0, Math.PI / 2, 0]} scale={0.728}>
            <group name="rig014" position={[0.036, -0.038, 0.033]} rotation={[-0.059, -0.115, 0.104]}>
              <primitive object={nodes.root_15} />
              <group name="m_1">
                <skinnedMesh name="Mesh016" geometry={nodes.Mesh016.geometry} material={materials['characters.002']} skeleton={nodes.Mesh016.skeleton} />
                <skinnedMesh name="Mesh016_1" geometry={nodes.Mesh016_1.geometry} material={materials['characters.002']} skeleton={nodes.Mesh016_1.skeleton} />
              </group>
            </group>
          </group>
          <spotLight intensity={1087.028} angle={0.12} penumbra={0.15} decay={2} color="#ffef00" position={[0.078, 11.625, 0.451]} rotation={[-1.591, -0.094, 0]} target={nodes.Spot.target}>
            <primitive object={nodes.Spot.target} position={[0, 0, -1]} />
          </spotLight>
          <spotLight angle={0.12} penumbra={0.15} decay={2} color="#0063ff" position={[-1.458, 11.625, 0.451]} rotation={[-1.591, -0.094, 0]} target={nodes.Spot001.target}>
            <primitive object={nodes.Spot001.target} position={[0, 0, -1]} />
          </spotLight>
          <spotLight intensity={1087.028} angle={0.12} penumbra={0.15} decay={2} color="#ff0012" position={[-0.744, 11.625, -0.858]} rotation={[-1.591, -0.094, 0]} target={nodes.Spot002.target}>
            <primitive object={nodes.Spot002.target} position={[0, 0, -1]} />
          </spotLight>
          <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials['material.001']} position={[1.396, 2.208, 0.832]} rotation={[0, 0.236, 0]} scale={0.021} />
          <mesh name="Object_5001" geometry={nodes.Object_5001.geometry} material={materials['material.001']} position={[-0.949, 2.204, 1.509]} rotation={[0, 0.236, 0]} scale={0.021} />
          <mesh name="node_1c880b5b_d49e_4b2d_a593_cb85239bf439_mesh0" geometry={nodes.node_1c880b5b_d49e_4b2d_a593_cb85239bf439_mesh0.geometry} material={materials['Material.031']} position={[-2.856, 3.276, -3.652]} rotation={[Math.PI / 2, 0, 2.706]} scale={[3.339, 1.875, 1.875]} />
          <mesh name="node_d2d5b2a1_746e_44c7_96c7_50adc24f8d8b_mesh0001" geometry={nodes.node_d2d5b2a1_746e_44c7_96c7_50adc24f8d8b_mesh0001.geometry} material={nodes.node_d2d5b2a1_746e_44c7_96c7_50adc24f8d8b_mesh0001.material} position={[-1.451, 4.551, -0.305]} rotation={[2.808, -0.414, -0.151]} scale={0.697} />
          <mesh name="Chair_02" geometry={nodes.Chair_02.geometry} material={materials['Color.001']} position={[1.945, 1.793, 2.095]} rotation={[Math.PI / 2, 0, 2.162]} scale={0.005} />
          <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['mat_15.002']} position={[0.278, -2.779, 0.265]} scale={4.118} />
          <mesh name="Couch_11" geometry={nodes.Couch_11.geometry} material={materials['Color.003']} position={[3.807, 1.3, 0.406]} rotation={[Math.PI / 2, 0, 1.606]} scale={0.008} />
          <mesh name="Chair_02001" geometry={nodes.Chair_02001.geometry} material={materials['Color.001']} position={[1.611, 1.793, 2.3]} rotation={[Math.PI / 2, 0, 2.536]} scale={0.005} />
          <mesh name="Plants_23" geometry={nodes.Plants_23.geometry} material={materials['Color.005']} position={[3.837, 1.309, 1.423]} rotation={[Math.PI / 2, 0, 0]} scale={0.008} />
          <mesh name="Plants_23001" geometry={nodes.Plants_23001.geometry} material={materials['Color.005']} position={[3.826, 1.309, -0.58]} rotation={[Math.PI / 2, 0, 0]} scale={0.008} />
          <mesh name="Shelf_08" geometry={nodes.Shelf_08.geometry} material={materials['Color.006']} position={[3.951, 1.295, -1.204]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.014} />
          <mesh name="Couch_11001" geometry={nodes.Couch_11001.geometry} material={materials['Color.003']} position={[-3.257, 1.317, 0.428]} rotation={[Math.PI / 2, 0, -1.535]} scale={0.008} />
          <mesh name="Plants_23002" geometry={nodes.Plants_23002.geometry} material={materials['Color.005']} position={[-3.286, 1.326, -0.59]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.008} />
          <mesh name="Plants_23003" geometry={nodes.Plants_23003.geometry} material={materials['Color.005']} position={[-3.276, 1.326, 1.414]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.008} />
          <mesh name="Shelf_08001" geometry={nodes.Shelf_08001.geometry} material={materials['Color.006']} position={[-3.295, 1.295, -1.204]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.014} />
          <mesh name="Audio_01" geometry={nodes.Audio_01.geometry} material={materials['Color.002']} position={[1.478, 1.966, 0.299]} rotation={[Math.PI / 2, 0, 0.493]} scale={0.007} />
          <mesh name="Audio_01001" geometry={nodes.Audio_01001.geometry} material={materials['Color.002']} position={[-0.968, 1.966, 0.299]} rotation={[Math.PI / 2, 0, -0.624]} scale={0.007} />
          <mesh name="TV_Stand_02" geometry={nodes.TV_Stand_02.geometry} material={materials['Color.002']} position={[0.286, 1.289, -3.463]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh name="GameConsole_01" geometry={nodes.GameConsole_01.geometry} material={materials['Color.002']} position={[0.76, 1.658, -2.48]} rotation={[Math.PI / 2, 0, 0]} scale={0.006} />
          <mesh name="GameConsole_02" geometry={nodes.GameConsole_02.geometry} material={materials['Color.002']} position={[-0.13, 1.454, -3.403]} rotation={[Math.PI / 2, 0, 0]} scale={0.015} />
          <mesh name="GameConsole_02001" geometry={nodes.GameConsole_02001.geometry} material={materials['Color.002']} position={[0.707, 1.454, -3.403]} rotation={[Math.PI / 2, 0, 0]} scale={0.015} />
          <mesh name="GameConsole_03_Part_02" geometry={nodes.GameConsole_03_Part_02.geometry} material={materials['Color.002']} position={[0.301, 1.68, -3.428]} rotation={[2.936, 0, 0]} scale={0.028} />
          <mesh name="GameConsole_01001" geometry={nodes.GameConsole_01001.geometry} material={materials['Color.002']} position={[-0.249, 1.881, -3.328]} rotation={[Math.PI / 2, 0, 0.739]} scale={0.006} />
          <mesh name="GameConsole_01002" geometry={nodes.GameConsole_01002.geometry} material={materials['Color.002']} position={[0.851, 1.881, -3.394]} rotation={[Math.PI / 2, 0, 0.217]} scale={0.006} />
          <mesh name="GameConsole_01003" geometry={nodes.GameConsole_01003.geometry} material={materials['Color.002']} position={[0.107, 1.658, -2.48]} rotation={[Math.PI / 2, 0, 0.758]} scale={0.006} />
          <mesh name="Coffee_Table_10" geometry={nodes.Coffee_Table_10.geometry} material={materials['Color.001']} position={[1.665, 1.789, 1.864]} rotation={[Math.PI / 2, 0, 0]} scale={0.007} />
          <mesh name="Cup_01" geometry={nodes.Cup_01.geometry} material={materials['Color.001']} position={[1.595, 2.139, 1.941]} rotation={[Math.PI / 2, 0, 1.574]} scale={0.007} />
          <mesh name="Cup_01001" geometry={nodes.Cup_01001.geometry} material={materials['Color.001']} position={[1.738, 2.139, 1.836]} rotation={[Math.PI / 2, 0, 0.697]} scale={0.007} />
          <mesh name="Chair_02002" geometry={nodes.Chair_02002.geometry} material={materials['Color.001']} position={[-1.445, 1.793, 2.045]} rotation={[Math.PI / 2, 0, -2.078]} scale={0.005} />
          <mesh name="Chair_02003" geometry={nodes.Chair_02003.geometry} material={materials['Color.001']} position={[-1.476, 1.793, 1.654]} rotation={[Math.PI / 2, 0, -1.703]} scale={0.005} />
          <mesh name="Coffee_Table_10001" geometry={nodes.Coffee_Table_10001.geometry} material={materials['Color.001']} position={[-1.113, 1.789, 1.901]} rotation={[Math.PI / 2, 0, 2.044]} scale={0.007} />
          <mesh name="Cup_01002" geometry={nodes.Cup_01002.geometry} material={materials['Color.001']} position={[-1.149, 2.139, 1.804]} rotation={[Math.PI / 2, 0, -2.665]} scale={0.007} />
          <mesh name="Cup_01003" geometry={nodes.Cup_01003.geometry} material={materials['Color.001']} position={[-1.121, 2.139, 1.979]} rotation={[Math.PI / 2, 0, 2.74]} scale={0.007} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/scene.glb')
