/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Web3.glb 
*/

import React, { useContext, useLayoutEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import * as THREE from "three";
import { AnimationContext } from "./AnimationContext";


gsap.registerPlugin(ScrollTrigger)
export function Web3(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('./models/Web3.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions,mixer } = useAnimations(animations, group)
    console.log("🚀 ~ Web3 ~ actions:", actions)
    const { currentModel,scrollDirection,animationTrigger } = useContext(AnimationContext);


      useLayoutEffect(() => {
        if (!actions || !mixer) return;
      
        const cameraAction = actions["CameraAction"];
      
        if (!cameraAction) return;
      
        // Play scroll animation (scrub)
        cameraAction.play();
        cameraAction.paused = true;
        const duration = cameraAction.getClip().duration;
      
        ScrollTrigger.create({
          trigger: ".second-section2",
          start: "top bottom",
          end: "bottom top",
          scrub: false,
          onUpdate: (self) => {
            cameraAction.time = self.progress * duration;
            mixer.update(0);
          },
        });
      

      
      }, [actions, mixer, animationTrigger]);
      
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature001" position={[0.818, 3.251, 1.633]} rotation={[0, -0.645, 0]} scale={0.219}>
          <primitive object={nodes.Bone} />
          <primitive object={nodes.Bone007} />
          <primitive object={nodes.Bone008} />
          <group name="Retopo_Sphere001">
            <skinnedMesh name="mesh001" geometry={nodes.mesh001.geometry} material={materials['Material.016']} skeleton={nodes.mesh001.skeleton} />
            <skinnedMesh name="mesh001_1" geometry={nodes.mesh001_1.geometry} material={materials.pants} skeleton={nodes.mesh001_1.skeleton} />
            <skinnedMesh name="mesh001_2" geometry={nodes.mesh001_2.geometry} material={materials.skin} skeleton={nodes.mesh001_2.skeleton} />
            <group name="Empty005" position={[0.606, -0.576, 0.21]} scale={1.043} />
            <group name="Empty006" position={[-0.672, -0.557, 0.358]} scale={0.834} />
          </group>
        </group>
        <group name="Armature005" position={[0.28, 4.998, -0.612]} rotation={[0, -0.933, 0]} scale={0.219}>
          <primitive object={nodes.Bone_1} />
          <primitive object={nodes.Bone007_1} />
          <primitive object={nodes.Bone008_1} />
          <group name="Retopo_Sphere005">
            <skinnedMesh name="mesh006" geometry={nodes.mesh006.geometry} material={materials['Material.016']} skeleton={nodes.mesh006.skeleton} />
            <skinnedMesh name="mesh006_1" geometry={nodes.mesh006_1.geometry} material={materials.pants} skeleton={nodes.mesh006_1.skeleton} />
            <skinnedMesh name="mesh006_2" geometry={nodes.mesh006_2.geometry} material={materials.skin} skeleton={nodes.mesh006_2.skeleton} />
            <group name="Empty011" position={[0.606, -0.576, 0.21]} scale={1.043} />
            <group name="Empty012" position={[-0.672, -0.557, 0.358]} scale={0.834} />
          </group>
        </group>
        <group name="Armature003" position={[-1.525, 3.689, -0.645]} rotation={[0, -0.526, 0]} scale={0.202}>
          <primitive object={nodes.Bone_2} />
          <primitive object={nodes.Bone007_2} />
          <primitive object={nodes.Bone008_2} />
          <group name="Retopo_Sphere003">
            <skinnedMesh name="mesh005" geometry={nodes.mesh005.geometry} material={materials['Material.008']} skeleton={nodes.mesh005.skeleton} />
            <skinnedMesh name="mesh005_1" geometry={nodes.mesh005_1.geometry} material={materials['pants.001']} skeleton={nodes.mesh005_1.skeleton} />
            <skinnedMesh name="mesh005_2" geometry={nodes.mesh005_2.geometry} material={materials['skin.001']} skeleton={nodes.mesh005_2.skeleton} />
            <group name="Empty009" position={[0.951, -0.059, 1.676]} rotation={[0, -0.594, 0]} scale={1.043} />
            <group name="Empty010" position={[-0.609, 0.103, 1.839]} scale={0.834} />
          </group>
        </group>
        {currentModel=="Model3" &&(
        <PerspectiveCamera name="Camera" makeDefault={true} far={1000} near={0.1} fov={16.461} position={[-19.814, 9.413, 17.558]} rotation={[-0.384, -0.922, -0.311]} />
        )}
        <mesh name="Cube014" geometry={nodes.Cube014.geometry} material={materials['Material.002']} position={[0.266, 2.292, -0.331]} />
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['Material.002']} position={[-1.531, 2.532, -0.334]} />
        <group name="Cylinder004" position={[0.266, 3.502, 0.475]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.481, 0.287, 0.481]}>
          <mesh name="Cylinder027" geometry={nodes.Cylinder027.geometry} material={materials['Material.022']} />
          <mesh name="Cylinder027_1" geometry={nodes.Cylinder027_1.geometry} material={materials['Material.003']} />
        </group>
        <group name="Cube016" position={[0.909, 5.096, -0.307]} rotation={[0.002, 0.587, -0.208]} scale={0.803}>
          <mesh name="Cube036" geometry={nodes.Cube036.geometry} material={materials['ArcadeMetal.001']} />
          <mesh name="Cube036_1" geometry={nodes.Cube036_1.geometry} material={materials['Material.011']} />
          <mesh name="Cube036_2" geometry={nodes.Cube036_2.geometry} material={materials['Material.016']} />
          <mesh name="Cube036_3" geometry={nodes.Cube036_3.geometry} material={materials['Material.013']} />
          <group name="Cylinder014" position={[0.043, -0.098, -0.004]} rotation={[-1.735, 1.532, 0.154]} scale={[0.027, 0.292, 0.027]}>
            <mesh name="Cylinder028_1" geometry={nodes.Cylinder028_1.geometry} material={nodes.Cylinder028_1.material} />
            <mesh name="Cylinder028_2" geometry={nodes.Cylinder028_2.geometry} material={materials.Blackk} />
          </group>
          <group name="Cylinder015" position={[0.07, -0.534, -0.167]} rotation={[-1.735, 1.532, -1.233]} scale={[0.021, 0.453, 0.021]}>
            <mesh name="Cylinder029_1" geometry={nodes.Cylinder029_1.geometry} material={materials['Material.010']} />
            <mesh name="Cylinder029_2" geometry={nodes.Cylinder029_2.geometry} material={materials.Blackk} />
          </group>
          <group name="Cylinder027_2" position={[0.229, -0.492, -0.005]} rotation={[-0.01, 0.006, 0.48]} scale={[0.021, 0.454, 0.02]}>
            <mesh name="Cylinder030_1" geometry={nodes.Cylinder030_1.geometry} material={materials['Material.009']} />
            <mesh name="Cylinder030_2" geometry={nodes.Cylinder030_2.geometry} material={materials.Blackk} />
          </group>
        </group>
        <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials['Material.022']} position={[-1.763, 3.24, -0.279]} rotation={[0, -0.491, 0]} />
        <mesh name="Cylinder028" geometry={nodes.Cylinder028.geometry} material={materials['Material.001']} position={[-1.064, 3.211, -0.062]} />
        <group name="Cube017" position={[0.238, 5.165, -1.08]} rotation={[2.671, 1.505, -2.7]} scale={0.803}>
          <mesh name="Cube038" geometry={nodes.Cube038.geometry} material={materials['ArcadeMetal.001']} />
          <mesh name="Cube038_1" geometry={nodes.Cube038_1.geometry} material={materials['Material.011']} />
          <mesh name="Cube038_2" geometry={nodes.Cube038_2.geometry} material={materials['Material.016']} />
          <mesh name="Cube038_3" geometry={nodes.Cube038_3.geometry} material={materials['Material.013']} />
        </group>
        <group name="Cylinder030" position={[-0.405, 4.634, -1.112]} rotation={[3.136, 0.321, 0.036]} scale={[0.016, 0.364, 0.016]}>
          <mesh name="Cylinder039" geometry={nodes.Cylinder039.geometry} material={materials['Material.010']} />
          <mesh name="Cylinder039_1" geometry={nodes.Cylinder039_1.geometry} material={materials.Blackk} />
        </group>
        <mesh name="Cylinder029" geometry={nodes.Cylinder029.geometry} material={materials['Material.002']} position={[-1.064, 3.421, -0.062]} scale={[0.135, 0.031, 0.135]} />
        <mesh name="Cylinder032" geometry={nodes.Cylinder032.geometry} material={materials['Material.002']} position={[-1.064, 3.831, -0.062]} scale={[0.135, 0.031, 0.135]} />
        <mesh name="Cylinder033" geometry={nodes.Cylinder033.geometry} material={nodes.Cylinder033.material} position={[0.089, 4.724, -0.146]} rotation={[0, 0, -Math.PI / 2]} scale={[0.018, 0.544, 0.018]} />
        <mesh name="Sphere" geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} position={[0.254, 4.769, -0.069]} scale={0.094} />
        <mesh name="Cylinder031" geometry={nodes.Cylinder031.geometry} material={materials['Material.001']} position={[-0.822, 2.836, 1.214]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cylinder034" geometry={nodes.Cylinder034.geometry} material={nodes.Cylinder034.material} position={[-1.075, 2.835, 0.623]} rotation={[Math.PI / 2, 0, 0]} scale={[0.135, 0.031, 0.135]} />
        <mesh name="Cylinder035" geometry={nodes.Cylinder035.geometry} material={materials['Material.001']} position={[1.188, 3.662, 2.041]} rotation={[0, 0, -Math.PI]} />
        <mesh name="Cylinder036" geometry={nodes.Cylinder036.geometry} material={materials['Metalic.001']} position={[0.083, 2.805, 2.137]} rotation={[0, 0, -Math.PI / 2]} scale={[0.018, 0.544, 0.018]} />
        <mesh name="Circle009" geometry={nodes.Circle009.geometry} material={nodes.Circle009.material} position={[-0.101, 3.154, 0.707]} rotation={[Math.PI / 2, 0, 0]} scale={0.112} />
        <mesh name="Circle013" geometry={nodes.Circle013.geometry} material={nodes.Circle013.material} position={[0.633, 3.513, 0.707]} rotation={[Math.PI / 2, 0, 0]} scale={0.112} />
        <mesh name="Cylinder037" geometry={nodes.Cylinder037.geometry} material={materials['spike.001']} position={[-1.064, 3.079, -0.062]} scale={[0.135, 0.031, 0.135]} />
        <mesh name="LAPTOP003" geometry={nodes.LAPTOP003.geometry} material={materials['BASE_LAPTOP_MAT.001']} position={[-1.751, 3.661, -0.359]} rotation={[0, -0.503, 0]} scale={[-0.164, -0.014, -0.105]} />
        <group name="SCREEN_LAPTOP003" position={[-1.832, 3.772, -0.215]} rotation={[-1.138, -0.227, -0.453]} scale={[-0.164, -0.014, -0.105]}>
          <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials['KEYBOARD.001']} />
          <mesh name="Cube006_1" geometry={nodes.Cube006_1.geometry} material={materials['CODE_SCREEN_MAT.001']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/Web3.glb')
