/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Web3.glb 
*/

import React, { useLayoutEffect } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'
import { useScrollAnimation } from '../../hooks/useScrollAnimation'
import * as THREE from "three"

export function Machine({ currentPage, ...props }) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('./models/Web3.glb')
  const { actions } = useAnimations(animations, group)
   console.log("🚀 ~ Machine ~ actions:", actions)
   useScrollAnimation({
      actions,
      animationName: 'camera action',
      currentPage,
      pageRange: [4, 6],
      excludedAnimations: [],
      excludedAll:true
    });

   
    useLayoutEffect(() => {
      const AnimationsToPlay = [
        'BODY', 'Hands', 'Eyes', 'Mouth', 'ball',
        'Paint', 'HandsClothe', 'BodyClothe', 'Buttons', 'BODY.001',
        'MetalDoor1Action', 'MetalDoor2Action'
      ]
    
      AnimationsToPlay.forEach((name) => {
        const action = actions[name]
        if (action) {
          action.setLoop(THREE.LoopOnce, 1) 
          action.clampWhenFinished = true
          action.timeScale = 0.5 
          action.reset().play()
        }
      })
    }, [])
    
    const isActive = currentPage >=4;

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" position={[0, -0.313, 0]} scale={0}>
          <group name="RootNode" position={[0, -2, 0]} scale={0}>
            <group name="Object_4" position={[0, -2, 0]} scale={0} />
            <group name="Object_16" position={[0, -2, 0]} scale={0} />
            <group name="Object_22" position={[0, -2, 0]} scale={0} />
            <group name="Object_7" position={[0, -2, 0]} scale={0} />
            <group name="Object_10" position={[0, -2, 0]} scale={0} />
            <group name="Object_19" position={[0, -2, 0]} scale={0} />
            <group name="Object_13" position={[0, -2, 0]} scale={0} />
          </group>
        </group>
        <group name="Sketchfab_model001" position={[0, 0.184, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.378} />
        <group name="cute_characterfbx" position={[0, 0.184, 0]} scale={0.004} />
        <group name="RootNode001" position={[0, 0.184, 0]} scale={0.004} />
        <group name="Cube" position={[0, 0.184, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.756} />
        <group name="Cylinder" position={[0, -0.313, 0]} scale={0} />
        <group name="Cube001" position={[0, 0.184, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.756} />
        <group name="Sphere" position={[0, 0.184, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.378} />
        <group name="Sphere001" position={[0, 0.184, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.378} />
        <group name="Cube002" position={[0, 0.184, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.355} />
        <group name="Cube012" position={[0, 0.184, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.378} />
        <group name="NurbsPath009" position={[-0.291, -0.129, -0.72]} rotation={[0.036, 0.59, 1.428]} scale={0.039} />
        <group name="Sketchfab_model002" position={[0, 1.262, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={2.363} />
        <group name="root" position={[0, 1.262, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={2.363} />
        <group name="GLTF_SceneRootNode" position={[0, 1.262, 0]} scale={2.363} />
        <group name="Sphere_0" position={[0, 1.262, 0]} scale={1.869} />
        <group name="Sphere001_1" position={[0.189, 1.155, 0.587]} scale={[0.053, 0.094, 0.068]} />
        <group name="Vert003_2" position={[0, 2.064, -0.03]} rotation={[-0.207, 0, 0]} scale={2.363} />
        <group name="Sphere002_3" position={[0, 1.262, 0]} scale={1.916} />
        <group name="Sphere004_4" position={[0, 1.291, 0]} scale={1.835} />
        <group name="Sphere005_5" position={[0, 0.362, 0.752]} scale={[0.058, 0.058, 0.028]} />
        <group name="Sphere006_6" position={[0, 0.165, 0.752]} scale={[0.058, 0.058, 0.028]} />
        <group name="Sphere007_7" position={[0, 1.218, 0]} scale={1.87} />
        <group name="Sphere003_8" position={[0, 1.228, 0]} scale={1.869} />
        <group name="Sphere008_9" position={[0, 1.228, 0]} scale={1.869} />
        <group name="Object_8006_10" position={[1.241, 0.073, 0]} rotation={[1.864, -0.217, 0.065]} scale={0.057} />
        <group name="Plane_11" position={[0, 1.057, 0.578]} rotation={[Math.PI / 2, 0, 0]} scale={0.069} />
        <group name="Cylinder_12" position={[0.89, 0.261, 0]} rotation={[0, 0, 1.112]} scale={0.208} />
        <group name="Cylinder001_13" position={[0.893, 0.259, 0]} rotation={[0, 0, 1.112]} scale={0.208} />
        <group name="Sphere009_14" position={[0.027, 2.468, -0.137]} scale={0.203} />
        <group name="Alien" position={[0, -3.443, 0]} scale={-0.01} />
        {isActive&&(
        <PerspectiveCamera name="Camera" makeDefault={isActive} far={1000} near={0.1} fov={31.006} position={[10.987, 5.839, 18.583]} rotation={[-0.272, 0.31, 0.085]} />
        )}
        <mesh name="Quad" geometry={nodes.Quad.geometry} material={materials['Material.009']} position={[2.977, 2.862, 0.62]} rotation={[-Math.PI, 0.862, -Math.PI]} scale={[6.275, 3.523, 3.523]} />
        <mesh name="MoviePanel" geometry={nodes.MoviePanel.geometry} material={materials.Metal} position={[3.003, 2.866, 0.597]} rotation={[0, -0.862, 0]} scale={[1.594, 1.574, 1.055]} />
        <mesh name="MetalDoorDring" geometry={nodes.MetalDoorDring.geometry} material={materials.Metal} position={[0, -0.858, 0]}>
          <mesh name="MetalDoor1" geometry={nodes.MetalDoor1.geometry} material={materials.Metal} position={[1.511, 0.042, 0]} />
          <mesh name="MetalDoor2" geometry={nodes.MetalDoor2.geometry} material={materials.Metal} position={[-1.511, 0.042, 0]} rotation={[Math.PI, 0, Math.PI]} />
        </mesh>
        <mesh name="GroundCylinderTransparent_1001" geometry={nodes.GroundCylinderTransparent_1001.geometry} material={materials['Material.007']} position={[0, -3.021, 0]} scale={[0.915, 1, 0.915]} />
        <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials['Material.007']} position={[0, -2.919, 0]} scale={2.164} />
        <group name="Object_4002" position={[0, -0.965, 0]} rotation={[Math.PI, 0, Math.PI]} scale={[0.009, 0, 0.009]}>
          <mesh name="Object_0001" geometry={nodes.Object_0001.geometry} material={materials['Material.010']} />
          <mesh name="Object_0001_1" geometry={nodes.Object_0001_1.geometry} material={materials['Material.016']} />
          <mesh name="Object_0001_2" geometry={nodes.Object_0001_2.geometry} material={materials['Material.013']} />
          <mesh name="Object_0001_3" geometry={nodes.Object_0001_3.geometry} material={materials['Material.012']} />
          <mesh name="Object_0001_4" geometry={nodes.Object_0001_4.geometry} material={materials['Material.014']} />
        </group>
        <mesh name="Object_4001" geometry={nodes.Object_4001.geometry} material={materials['Material.015']} position={[0, -0.965, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.009, 0, 0.009]} />
        <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials['Material.006']} position={[0, 1.155, 0.587]} scale={0} />
        <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials['Material.015']} position={[0, 2.064, -0.03]} scale={0} />
        <mesh name="Object_16001" geometry={nodes.Object_16001.geometry} material={materials['Material.006']} position={[0, 0.264, 0.752]} scale={0} />
        <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials['Material.015']} position={[0, 0.221, 0]} scale={0} />
        <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials['Material.015']} position={[0, -0.965, 0]} scale={0} />
        <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials['Material.015']} position={[0, 0.11, 0.006]} scale={0} />
        <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials['Material.006']} position={[0, 1.057, 0.578]} scale={0} />
        <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials['Material.015']} position={[0, 0.236, 0]} scale={0} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/Web3.glb')
